; generated by weavec2
; source: test/performance/wir/0005_let_local.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; let x
  ; return
  %t0 = add i32 40, 2
  ret i32 %t0
}

