; generated by weavec2
; source: test/performance/wir/0012_i64_arithmetic.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; let a
  ; let b
  %t0 = mul i64 2, 11
  ; let c
  %t1 = add i64 20, %t0
  ; let d
  ; return
  %t2 = trunc i64 %t1 to i32
  ret i32 %t2
}

