; generated by weavec2
; source: test/performance/wir/0016_extern_malloc_free.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 8)
  ; let p
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %else
then:
  ; then
  ; return
  ret i32 0
else:
  ; else
  call void @free(ptr %t0)
  ; return
  ret i32 42
}

