; generated by weavec2
; source: test/performance/wir/0019_call_void.wir
; core-version: 1

; declarations

declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  call void @free(ptr null)
  ; return
  ret i32 42
}

