; generated by weavec2
; source: test/performance/wir/0020_call_i64.wir
; core-version: 1

; function: answer64
; params: none
; returns: i64
define i64 @answer64() {
entry:
  ; return
  ret i64 42
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i64 @answer64()
  %t1 = trunc i64 %t0 to i32
  ret i32 %t1
}

