; generated by weavec2
; source: test/performance/wir/0024_buffer_like_smoke.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 24)
  ; let buffer
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @malloc(i64 8)
  ; let data
  ; if condition
  %t3 = icmp eq ptr %t2, null
  br i1 %t3, label %then1, label %endif1
then1:
  ; then
  call void @free(ptr %t0)
  ; return
  ret i32 0
endif1:
  store ptr %t2, ptr %t0
  %t4 = getelementptr i8, ptr %t0, i64 8
  store i64 1, ptr %t4
  %t5 = getelementptr i8, ptr %t0, i64 16
  store i64 8, ptr %t5
  %t6 = trunc i32 42 to i8
  store i8 %t6, ptr %t2
  %t7 = load ptr, ptr %t0
  ; let data2
  %t8 = load i8, ptr %t7
  %t9 = zext i8 %t8 to i32
  ; let x
  call void @free(ptr %t2)
  call void @free(ptr %t0)
  ; return
  ret i32 %t9
}

