; generated by weavec2
; source: test/performance/wir/0025_ptr_params_call_i32.wir
; core-version: 1

; function: same_ptr
; params: ptr, ptr
; returns: i32
define i32 @same_ptr(ptr %a, ptr %b) {
entry:
  ; if condition
  %t0 = icmp eq ptr %a, %b
  br i1 %t0, label %then, label %else
then:
  ; then
  ; return
  ret i32 42
else:
  ; else
  ; return
  ret i32 0
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @same_ptr(ptr null, ptr null)
  ret i32 %t0
}

