; generated by weavec2
; source: test/performance/wir/0026_bool_return.wir
; core-version: 1

; function: same
; params: i1
; returns: i1
define i1 @same(i1 %x) {
entry:
  ; return
  ret i1 %x
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = call i1 @same(i1 true)
  br i1 %t0, label %then, label %else
then:
  ; then
  ; return
  ret i32 42
else:
  ; else
  ; return
  ret i32 0
}

