; generated by weavec2
; source: test/performance/wir/0030_i64_sub_eq.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = sub i64 50, 8
  %t1 = icmp eq i64 %t0, 42
  br i1 %t1, label %then, label %else
then:
  ; then
  ; return
  ret i32 42
else:
  ; else
  ; return
  ret i32 0
}

