; generated by weavec2
; source: test/performance/wir/0031_not_bool.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = xor i1 false, true
  br i1 %t0, label %then, label %else
then:
  ; then
  ; return
  ret i32 42
else:
  ; else
  ; return
  ret i32 0
}

