; generated by weavec2
; source: test/performance/wir/0039_i64_ge_gt.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = icmp sgt i64 10, 9
  br i1 %t0, label %then, label %else
then:
  ; then
  br label %endif
else:
  ; else
  ; return
  ret i32 0
endif:
  ; if condition
  %t1 = icmp sge i64 10, 10
  br i1 %t1, label %then1, label %else1
then1:
  ; then
  ; return
  ret i32 42
else1:
  ; else
  ; return
  ret i32 0
}

