; generated by weavec2
; source: test/performance/wir/0040_call_bool_direct.wir
; core-version: 1

; function: is_answer
; params: i32
; returns: i1
define i1 @is_answer(i32 %x) {
entry:
  ; return
  %t0 = icmp eq i32 %x, 42
  ret i1 %t0
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = call i1 @is_answer(i32 42)
  br i1 %t0, label %then, label %else
then:
  ; then
  ; return
  ret i32 42
else:
  ; else
  ; return
  ret i32 0
}

