; generated by weavec2
; source: test/performance/wir/0046_forward_function_call.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @answer()
  ret i32 %t0
}

; function: answer
; params: none
; returns: i32
define i32 @answer() {
entry:
  ; return
  ret i32 42
}

