; generated by weavec2
; source: test/performance/wir/0054_debug_marker.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %x.addr = alloca i32
  ; let x
  store i32 40, ptr %x.addr
  ; debug start: this is my debug zone
  ; set x
  %t0 = load i32, ptr %x.addr
  %t1 = add i32 %t0, 2
  store i32 %t1, ptr %x.addr
  ; debug end: this is my debug zone
  ; return
  %t2 = load i32, ptr %x.addr
  ret i32 %t2
}

