; generated by weavec2
; source: test/performance/wir/0068_binary_search_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %t0 = sext i32 %index to i64
  %t1 = getelementptr i32, ptr %base, i64 %t0
  ret ptr %t1
}

; function: search7
; params: ptr, i32
; returns: i32
define i32 @search7(ptr %items, i32 %target) {
entry:
  %low.addr = alloca i32
  %high.addr = alloca i32
  %result.addr = alloca i32
  %active.addr = alloca i32
  ; let low
  store i32 0, ptr %low.addr
  ; let high
  store i32 6, ptr %high.addr
  ; let result
  store i32 -1, ptr %result.addr
  ; let active
  store i32 1, ptr %active.addr
  ; while condition
  br label %while.pre
while.pre:
  %result.init0 = load i32, ptr %result.addr
  %active.init0 = load i32, ptr %active.addr
  %low.init0 = load i32, ptr %low.addr
  %high.init0 = load i32, ptr %high.addr
  br label %while.cond
while.cond:
  %result.phi0 = phi i32 [%result.init0, %while.pre], [%result.merge1, %while.latch]
  %active.phi0 = phi i32 [%active.init0, %while.pre], [%active.merge1, %while.latch]
  %low.phi0 = phi i32 [%low.init0, %while.pre], [%low.merge1, %while.latch]
  %high.phi0 = phi i32 [%high.init0, %while.pre], [%high.merge1, %while.latch]
  %t0 = icmp sle i32 %low.phi0, %high.phi0
  %t1 = icmp ne i32 %active.phi0, 0
  %t2 = and i1 %t0, %t1
  br i1 %t2, label %while.body, label %while.exit-merge
while.body:
  ; while body
  %t3 = add i32 %low.phi0, %high.phi0
  %t4 = sdiv i32 %t3, 2
  ; let mid
  %t5 = call ptr @elem_ptr(ptr %items, i32 %t4)
  %t6 = load i32, ptr %t5
  ; let value
  ; if condition
  %t7 = icmp eq i32 %t6, %target
  br i1 %t7, label %then1, label %else1
then1:
  ; then
  ; set result
  %t8 = add i32 %low.phi0, %high.phi0
  %result.next10 = sdiv i32 %t8, 2
  ; set active
  %active.next10 = add i32 0, 0
  br label %endif1
else1:
  ; else
  ; if condition
  %t9 = icmp slt i32 %t6, %target
  br i1 %t9, label %then2, label %else2
then2:
  ; then
  ; set low
  %low.next20 = add i32 %t4, 1
  br label %endif2
else2:
  ; else
  ; set high
  %high.next21 = sub i32 %t4, 1
  br label %endif2
endif2:
  %low.merge2 = phi i32 [%low.next20, %then2], [%low.phi0, %else2]
  %high.merge2 = phi i32 [%high.phi0, %then2], [%high.next21, %else2]
  br label %endif1
endif1:
  %low.merge1 = phi i32 [%low.phi0, %then1], [%low.merge2, %endif2]
  %high.merge1 = phi i32 [%high.phi0, %then1], [%high.merge2, %endif2]
  %result.merge1 = phi i32 [%result.next10, %then1], [%result.phi0, %endif2]
  %active.merge1 = phi i32 [%active.next10, %then1], [%active.phi0, %endif2]
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %result.phi0, ptr %result.addr
  store i32 %active.phi0, ptr %active.addr
  store i32 %low.phi0, ptr %low.addr
  store i32 %high.phi0, ptr %high.addr
  br label %while.end
while.end:
  ; return
  %t10 = load i32, ptr %result.addr
  ret i32 %t10
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 28)
  ; let items
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @elem_ptr(ptr %t0, i32 0)
  store i32 1, ptr %t2
  %t3 = call ptr @elem_ptr(ptr %t0, i32 1)
  store i32 3, ptr %t3
  %t4 = call ptr @elem_ptr(ptr %t0, i32 2)
  store i32 5, ptr %t4
  %t5 = call ptr @elem_ptr(ptr %t0, i32 3)
  store i32 7, ptr %t5
  %t6 = call ptr @elem_ptr(ptr %t0, i32 4)
  store i32 9, ptr %t6
  %t7 = call ptr @elem_ptr(ptr %t0, i32 5)
  store i32 11, ptr %t7
  %t8 = call ptr @elem_ptr(ptr %t0, i32 6)
  store i32 13, ptr %t8
  %t9 = call i32 @search7(ptr %t0, i32 9)
  ; let index
  call void @free(ptr %t0)
  ; return
  %t10 = add i32 %t9, 38
  ret i32 %t10
}

