; generated by weavec2
; source: test/performance/wir/0070_horner_polynomial_i32.wir
; core-version: 1

; function: horner3
; params: i32
; returns: i32
define i32 @horner3(i32 %x) {
entry:
  %acc.addr = alloca i32
  %i.addr = alloca i32
  ; let acc
  store i32 1, ptr %acc.addr
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre
while.pre:
  %acc.init0 = load i32, ptr %acc.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %acc.phi0 = phi i32 [%acc.init0, %while.pre], [%acc.next0, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp slt i32 %i.phi0, 3
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; let next (deferred)
  ; set acc
  %t1 = mul i32 %acc.phi0, %x
  %acc.next0 = add i32 %t1, 2
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %acc.phi0, ptr %acc.addr
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t2 = load i32, ptr %acc.addr
  ret i32 %t2
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @horner3(i32 3)
  %t1 = sub i32 %t0, 11
  ret i32 %t1
}

