; generated by weavec2
; source: test/performance/wir/0086_max_of_three_i32.wir
; core-version: 1

; function: max3
; params: i32, i32, i32
; returns: i32
define i32 @max3(i32 %a, i32 %b, i32 %c) {
entry:
  %m.addr = alloca i32
  ; let m
  store i32 %a, ptr %m.addr
  ; if condition
  %t0 = load i32, ptr %m.addr
  %t1 = icmp sgt i32 %b, %t0
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; set m
  store i32 %b, ptr %m.addr
  br label %endif
endif:
  ; if condition
  %t2 = load i32, ptr %m.addr
  %t3 = icmp sgt i32 %c, %t2
  br i1 %t3, label %then1, label %endif1
then1:
  ; then
  ; set m
  store i32 %c, ptr %m.addr
  br label %endif1
endif1:
  ; return
  %t4 = load i32, ptr %m.addr
  ret i32 %t4
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @max3(i32 17, i32 42, i32 23)
  ret i32 %t0
}

