; generated by weavec2
; source: test/performance/wir/0087_popcount_i32.wir
; core-version: 1

; function: popcount
; params: i32
; returns: i32
define i32 @popcount(i32 %v) {
entry:
  %n.addr = alloca i32
  %bits.addr = alloca i32
  ; let n
  store i32 %v, ptr %n.addr
  ; let bits
  store i32 0, ptr %bits.addr
  ; while condition
  br label %while.pre
while.pre:
  %bits.init0 = load i32, ptr %bits.addr
  %n.init0 = load i32, ptr %n.addr
  br label %while.cond
while.cond:
  %bits.phi0 = phi i32 [%bits.init0, %while.pre], [%bits.merge1, %while.latch]
  %n.phi0 = phi i32 [%n.init0, %while.pre], [%n.next0, %while.latch]
  %t0 = icmp sgt i32 %n.phi0, 0
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t1 = srem i32 %n.phi0, 2
  %t2 = icmp ne i32 %t1, 0
  br i1 %t2, label %then1, label %endif1
then1:
  ; then
  ; set bits
  %bits.next10 = add i32 %bits.phi0, 1
  br label %endif1
endif1:
  %bits.merge1 = phi i32 [%bits.next10, %then1], [%bits.phi0, %while.body]
  ; set n
  %n.next0 = sdiv i32 %n.phi0, 2
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %bits.phi0, ptr %bits.addr
  store i32 %n.phi0, ptr %n.addr
  br label %while.end
while.end:
  ; return
  %t3 = load i32, ptr %bits.addr
  ret i32 %t3
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @popcount(i32 29)
  ret i32 %t0
}

