; generated by weavec2
; source: test/performance/wir/0088_digital_sum_i32.wir
; core-version: 1

; function: digital_sum
; params: i32
; returns: i32
define i32 @digital_sum(i32 %n) {
entry:
  %x.addr = alloca i32
  %total.addr = alloca i32
  ; let x
  store i32 %n, ptr %x.addr
  ; let total
  store i32 0, ptr %total.addr
  ; while condition
  br label %while.pre
while.pre:
  %total.init0 = load i32, ptr %total.addr
  %x.init0 = load i32, ptr %x.addr
  br label %while.cond
while.cond:
  %total.phi0 = phi i32 [%total.init0, %while.pre], [%total.next0, %while.latch]
  %x.phi0 = phi i32 [%x.init0, %while.pre], [%x.next0, %while.latch]
  %t0 = icmp sgt i32 %x.phi0, 0
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set total
  %t1 = srem i32 %x.phi0, 10
  %total.next0 = add i32 %total.phi0, %t1
  ; set x
  %x.next0 = sdiv i32 %x.phi0, 10
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %total.phi0, ptr %total.addr
  store i32 %x.phi0, ptr %x.addr
  br label %while.end
while.end:
  ; return
  %t2 = load i32, ptr %total.addr
  ret i32 %t2
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @digital_sum(i32 9876)
  ret i32 %t0
}

