; generated by weavec2
; source: test/performance/wir/0089_tribonacci_iter_i32.wir
; core-version: 1

; function: trib
; params: i32
; returns: i32
define i32 @trib(i32 %n) {
entry:
  %a.addr = alloca i32
  %b.addr = alloca i32
  %c.addr = alloca i32
  %i.addr = alloca i32
  ; if condition
  %t0 = icmp sle i32 %n, 1
  br i1 %t0, label %then, label %endif
then:
  ; then
  ; return
  ret i32 %n
endif:
  ; if condition
  %t1 = icmp eq i32 %n, 2
  br i1 %t1, label %then1, label %endif1
then1:
  ; then
  ; return
  ret i32 1
endif1:
  ; let a
  store i32 0, ptr %a.addr
  ; let b
  store i32 1, ptr %b.addr
  ; let c
  store i32 1, ptr %c.addr
  ; let i
  store i32 3, ptr %i.addr
  ; while condition
  br label %while.pre2
while.pre2:
  %a.init2 = load i32, ptr %a.addr
  %b.init2 = load i32, ptr %b.addr
  %c.init2 = load i32, ptr %c.addr
  %i.init2 = load i32, ptr %i.addr
  br label %while.cond2
while.cond2:
  %a.phi2 = phi i32 [%a.init2, %while.pre2], [%b.phi2, %while.latch2]
  %b.phi2 = phi i32 [%b.init2, %while.pre2], [%c.phi2, %while.latch2]
  %c.phi2 = phi i32 [%c.init2, %while.pre2], [%c.next2, %while.latch2]
  %i.phi2 = phi i32 [%i.init2, %while.pre2], [%i.next2, %while.latch2]
  %t2 = icmp sle i32 %i.phi2, %n
  br i1 %t2, label %while.body2, label %while.exit-merge2
while.body2:
  ; while body
  %t3 = add i32 %a.phi2, %b.phi2
  %t4 = add i32 %t3, %c.phi2
  ; let next
  ; set a
  %a.next2 = add i32 %b.phi2, 0
  ; set b
  %b.next2 = add i32 %c.phi2, 0
  ; set c
  %c.next2 = add i32 %t4, 0
  ; set i
  %i.next2 = add i32 %i.phi2, 1
  br label %while.latch2
while.latch2:
  br label %while.cond2
while.exit-merge2:
  ; sync loop-carried locals to stack
  store i32 %a.phi2, ptr %a.addr
  store i32 %b.phi2, ptr %b.addr
  store i32 %c.phi2, ptr %c.addr
  store i32 %i.phi2, ptr %i.addr
  br label %while.end2
while.end2:
  ; return
  %t5 = load i32, ptr %c.addr
  ret i32 %t5
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @trib(i32 10)
  ret i32 %t0
}

