; generated by weavec2
; source: test/performance/wir/0090_floor_sqrt_i32.wir
; core-version: 1

; function: floor_sqrt
; params: i32
; returns: i32
define i32 @floor_sqrt(i32 %n) {
entry:
  %r.addr = alloca i32
  %t.addr = alloca i32
  ; let r
  store i32 0, ptr %r.addr
  ; let t
  store i32 1, ptr %t.addr
  ; while condition
  br label %while.pre
while.pre:
  %r.init0 = load i32, ptr %r.addr
  %t.init0 = load i32, ptr %t.addr
  br label %while.cond
while.cond:
  %r.phi0 = phi i32 [%r.init0, %while.pre], [%t.phi0, %while.latch]
  %t.phi0 = phi i32 [%t.init0, %while.pre], [%t.next0, %while.latch]
  %t0 = mul i32 %t.phi0, %t.phi0
  %t1 = icmp sle i32 %t0, %n
  br i1 %t1, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set r
  ; set t
  %t.next0 = add i32 %t.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %r.phi0, ptr %r.addr
  store i32 %t.phi0, ptr %t.addr
  br label %while.end
while.end:
  ; return
  %t2 = load i32, ptr %r.addr
  ret i32 %t2
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @floor_sqrt(i32 200)
  ret i32 %t0
}

