; generated by weavec2
; source: test/performance/wir/0095_abs_i32.wir
; core-version: 1

; function: abs_i32
; params: i32
; returns: i32
define i32 @abs_i32(i32 %x) {
entry:
  ; if condition
  %t0 = icmp slt i32 %x, 0
  br i1 %t0, label %then, label %else
then:
  ; then
  ; return
  %t1 = sub i32 0, %x
  ret i32 %t1
else:
  ; else
  ; return
  ret i32 %x
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @abs_i32(i32 -123)
  ret i32 %t0
}

