; generated by weavec2
; source: test/performance/wir/0100_reverse_digits_i32.wir
; core-version: 1

; function: reverse_digits
; params: i32
; returns: i32
define i32 @reverse_digits(i32 %n) {
entry:
  %x.addr = alloca i32
  %rev.addr = alloca i32
  ; let x
  store i32 %n, ptr %x.addr
  ; let rev
  store i32 0, ptr %rev.addr
  ; while condition
  br label %while.pre
while.pre:
  %rev.init0 = load i32, ptr %rev.addr
  %x.init0 = load i32, ptr %x.addr
  br label %while.cond
while.cond:
  %rev.phi0 = phi i32 [%rev.init0, %while.pre], [%rev.next0, %while.latch]
  %x.phi0 = phi i32 [%x.init0, %while.pre], [%x.next0, %while.latch]
  %t0 = icmp sgt i32 %x.phi0, 0
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set rev
  %t1 = mul i32 %rev.phi0, 10
  %t2 = srem i32 %x.phi0, 10
  %rev.next0 = add i32 %t1, %t2
  ; set x
  %x.next0 = sdiv i32 %x.phi0, 10
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %rev.phi0, ptr %rev.addr
  store i32 %x.phi0, ptr %x.addr
  br label %while.end
while.end:
  ; return
  %t3 = load i32, ptr %rev.addr
  ret i32 %t3
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @reverse_digits(i32 12034)
  ret i32 %t0
}

