; generated by weavec2
; source: test/performance/wir/0106_clamp_i32.wir
; core-version: 1

; function: clamp
; params: i32, i32, i32
; returns: i32
define i32 @clamp(i32 %v, i32 %lo, i32 %hi) {
entry:
  %out.addr = alloca i32
  ; let out
  store i32 %v, ptr %out.addr
  ; if condition
  %t0 = load i32, ptr %out.addr
  %t1 = icmp slt i32 %t0, %lo
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; set out
  store i32 %lo, ptr %out.addr
  br label %endif
endif:
  ; if condition
  %t2 = load i32, ptr %out.addr
  %t3 = icmp sgt i32 %t2, %hi
  br i1 %t3, label %then1, label %endif1
then1:
  ; then
  ; set out
  store i32 %hi, ptr %out.addr
  br label %endif1
endif1:
  ; return
  %t4 = load i32, ptr %out.addr
  ret i32 %t4
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @clamp(i32 150, i32 10, i32 99)
  ret i32 %t0
}

