; generated by weavec2
; source: test/performance/wir/0108_hailstone_peak_i32.wir
; core-version: 1

; function: hailstone_peak
; params: i32
; returns: i32
define i32 @hailstone_peak(i32 %start) {
entry:
  %n.addr = alloca i32
  %peak.addr = alloca i32
  ; let n
  store i32 %start, ptr %n.addr
  ; let peak
  store i32 %start, ptr %peak.addr
  ; while condition
  br label %while.pre
while.pre:
  %peak.init0 = load i32, ptr %peak.addr
  %n.init0 = load i32, ptr %n.addr
  br label %while.cond
while.cond:
  %peak.phi0 = phi i32 [%peak.init0, %while.pre], [%peak.merge1, %while.latch]
  %n.phi0 = phi i32 [%n.init0, %while.pre], [%n.merge2, %while.latch]
  %t0 = icmp ne i32 %n.phi0, 1
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t1 = icmp sgt i32 %n.phi0, %peak.phi0
  br i1 %t1, label %then1, label %endif1
then1:
  ; then
  ; set peak
  %peak.next10 = add i32 %n.phi0, 0
  br label %endif1
endif1:
  %peak.merge1 = phi i32 [%peak.next10, %then1], [%peak.phi0, %while.body]
  ; if condition
  %t2 = srem i32 %n.phi0, 2
  %t3 = icmp eq i32 %t2, 0
  br i1 %t3, label %then2, label %else2
then2:
  ; then
  ; set n
  %n.next20 = sdiv i32 %n.phi0, 2
  br label %endif2
else2:
  ; else
  ; set n
  %t4 = mul i32 %n.phi0, 3
  %n.next21 = add i32 %t4, 1
  br label %endif2
endif2:
  %n.merge2 = phi i32 [%n.next20, %then2], [%n.next21, %else2]
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %peak.phi0, ptr %peak.addr
  store i32 %n.phi0, ptr %n.addr
  br label %while.end
while.end:
  ; return
  %t5 = load i32, ptr %peak.addr
  ret i32 %t5
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @hailstone_peak(i32 27)
  ret i32 %t0
}

