; generated by weavec2
; source: test/performance/wir/0110_nested_sum_ij_i32.wir
; core-version: 1

; function: nested_sum
; params: i32
; returns: i32
define i32 @nested_sum(i32 %n) {
entry:
  %i.addr = alloca i32
  %total.addr = alloca i32
  %j.addr = alloca i32
  ; let i
  store i32 1, ptr %i.addr
  ; let total
  store i32 0, ptr %total.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp sle i32 %t0, %n
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let j
  store i32 1, ptr %j.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %total.init1 = load i32, ptr %total.addr
  %j.init1 = load i32, ptr %j.addr
  br label %while.cond1
while.cond1:
  %total.phi1 = phi i32 [%total.init1, %while.pre1], [%total.next1, %while.latch1]
  %j.phi1 = phi i32 [%j.init1, %while.pre1], [%j.next1, %while.latch1]
  %t2 = icmp sle i32 %j.phi1, %n
  br i1 %t2, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  ; set total
  %t3 = load i32, ptr %i.addr
  %t4 = mul i32 %t3, %j.phi1
  %total.next1 = add i32 %total.phi1, %t4
  ; set j
  %j.next1 = add i32 %j.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %total.phi1, ptr %total.addr
  store i32 %j.phi1, ptr %j.addr
  br label %while.end1
while.end1:
  ; set i
  %t5 = load i32, ptr %i.addr
  %t6 = add i32 %t5, 1
  store i32 %t6, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t7 = load i32, ptr %total.addr
  ret i32 %t7
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @nested_sum(i32 4)
  ret i32 %t0
}

