; generated by weavec2
; source: test/performance/wir/0112_sum_evens_to_n_i32.wir
; core-version: 1

; function: sum_evens_to
; params: i32
; returns: i32
define i32 @sum_evens_to(i32 %n) {
entry:
  %v.addr = alloca i32
  %total.addr = alloca i32
  ; let v
  store i32 2, ptr %v.addr
  ; let total
  store i32 0, ptr %total.addr
  ; while condition
  br label %while.pre
while.pre:
  %total.init0 = load i32, ptr %total.addr
  %v.init0 = load i32, ptr %v.addr
  br label %while.cond
while.cond:
  %total.phi0 = phi i32 [%total.init0, %while.pre], [%total.next0, %while.latch]
  %v.phi0 = phi i32 [%v.init0, %while.pre], [%v.next0, %while.latch]
  %t0 = icmp sle i32 %v.phi0, %n
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set total
  %total.next0 = add i32 %total.phi0, %v.phi0
  ; set v
  %v.next0 = add i32 %v.phi0, 2
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %total.phi0, ptr %total.addr
  store i32 %v.phi0, ptr %v.addr
  br label %while.end
while.end:
  ; return
  %t1 = load i32, ptr %total.addr
  ret i32 %t1
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @sum_evens_to(i32 20)
  ret i32 %t0
}

