; generated by weavec2
; source: test/performance/wir/0114_power_of_two_i32.wir
; core-version: 1

; function: is_pow2
; params: i32
; returns: i32
define i32 @is_pow2(i32 %n) {
entry:
  %v.addr = alloca i32
  ; if condition
  %t0 = icmp sle i32 %n, 0
  br i1 %t0, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  ; let v
  store i32 %n, ptr %v.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %v.init1 = load i32, ptr %v.addr
  br label %while.cond1
while.cond1:
  %v.phi1 = phi i32 [%v.init1, %while.pre1], [%v.next1, %while.latch1]
  %t1 = icmp sgt i32 %v.phi1, 1
  %t2 = srem i32 %v.phi1, 2
  %t3 = icmp eq i32 %t2, 0
  %t4 = and i1 %t1, %t3
  br i1 %t4, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  ; set v
  %v.next1 = sdiv i32 %v.phi1, 2
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %v.phi1, ptr %v.addr
  br label %while.end1
while.end1:
  ; if condition
  %t5 = load i32, ptr %v.addr
  %t6 = icmp eq i32 %t5, 1
  br i1 %t6, label %then2, label %else2
then2:
  ; then
  ; return
  ret i32 1
else2:
  ; else
  ; return
  ret i32 0
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @is_pow2(i32 64)
  ret i32 %t0
}

