; generated by weavec2
; source: test/performance/wir/0115_sum_powers_of_two_i32.wir
; core-version: 1

; function: sum_powers
; params: i32
; returns: i32
define i32 @sum_powers(i32 %k) {
entry:
  %i.addr = alloca i32
  %p.addr = alloca i32
  %total.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; let p
  store i32 1, ptr %p.addr
  ; let total
  store i32 0, ptr %total.addr
  ; while condition
  br label %while.pre
while.pre:
  %total.init0 = load i32, ptr %total.addr
  %p.init0 = load i32, ptr %p.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %total.phi0 = phi i32 [%total.init0, %while.pre], [%total.next0, %while.latch]
  %p.phi0 = phi i32 [%p.init0, %while.pre], [%p.next0, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp sle i32 %i.phi0, %k
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set total
  %total.next0 = add i32 %total.phi0, %p.phi0
  ; set p
  %p.next0 = mul i32 %p.phi0, 2
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %total.phi0, ptr %total.addr
  store i32 %p.phi0, ptr %p.addr
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t1 = load i32, ptr %total.addr
  ret i32 %t1
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @sum_powers(i32 5)
  ret i32 %t0
}

