; generated by weavec2
; source: test/performance/wir/0116_trailing_zeros_i32.wir
; core-version: 1

; function: trailing_zeros
; params: i32
; returns: i32
define i32 @trailing_zeros(i32 %v) {
entry:
  %n.addr = alloca i32
  %count.addr = alloca i32
  ; let n
  store i32 %v, ptr %n.addr
  ; let count
  store i32 0, ptr %count.addr
  ; while condition
  br label %while.pre
while.pre:
  %count.init0 = load i32, ptr %count.addr
  %n.init0 = load i32, ptr %n.addr
  br label %while.cond
while.cond:
  %count.phi0 = phi i32 [%count.init0, %while.pre], [%count.next0, %while.latch]
  %n.phi0 = phi i32 [%n.init0, %while.pre], [%n.next0, %while.latch]
  %t0 = icmp sgt i32 %n.phi0, 0
  %t1 = srem i32 %n.phi0, 2
  %t2 = icmp eq i32 %t1, 0
  %t3 = and i1 %t0, %t2
  br i1 %t3, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set count
  %count.next0 = add i32 %count.phi0, 1
  ; set n
  %n.next0 = sdiv i32 %n.phi0, 2
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %count.phi0, ptr %count.addr
  store i32 %n.phi0, ptr %n.addr
  br label %while.end
while.end:
  ; return
  %t4 = load i32, ptr %count.addr
  ret i32 %t4
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @trailing_zeros(i32 96)
  ret i32 %t0
}

