; generated by weavec2
; source: test/performance/wir/0118_bubble_sort5_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %t0 = sext i32 %index to i64
  %t1 = getelementptr i32, ptr %base, i64 %t0
  ret ptr %t1
}

; function: bubble_sort5
; params: ptr
; returns: void
define void @bubble_sort5(ptr %items) {
entry:
  %pass.addr = alloca i32
  %j.addr = alloca i32
  ; let pass
  store i32 0, ptr %pass.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %pass.addr
  %t1 = icmp slt i32 %t0, 4
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let j
  store i32 0, ptr %j.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %j.init1 = load i32, ptr %j.addr
  br label %while.cond1
while.cond1:
  %j.phi1 = phi i32 [%j.init1, %while.pre1], [%j.next1, %while.latch1]
  %t2 = load i32, ptr %pass.addr
  %t3 = sub i32 4, %t2
  %t4 = icmp slt i32 %j.phi1, %t3
  br i1 %t4, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  %t5 = call ptr @elem_ptr(ptr %items, i32 %j.phi1)
  %t6 = load i32, ptr %t5
  ; let a
  %t7 = add i32 %j.phi1, 1
  %t8 = call ptr @elem_ptr(ptr %items, i32 %t7)
  %t9 = load i32, ptr %t8
  ; let b
  ; if condition
  %t10 = icmp sgt i32 %t6, %t9
  br i1 %t10, label %then2, label %endif2
then2:
  ; then
  %t11 = call ptr @elem_ptr(ptr %items, i32 %j.phi1)
  store i32 %t9, ptr %t11
  %t12 = add i32 %j.phi1, 1
  %t13 = call ptr @elem_ptr(ptr %items, i32 %t12)
  store i32 %t6, ptr %t13
  br label %endif2
endif2:
  ; set j
  %j.next1 = add i32 %j.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %j.phi1, ptr %j.addr
  br label %while.end1
while.end1:
  ; set pass
  %t14 = load i32, ptr %pass.addr
  %t15 = add i32 %t14, 1
  store i32 %t15, ptr %pass.addr
  br label %while.cond
while.end:
  ret void
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 20)
  ; let items
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @elem_ptr(ptr %t0, i32 0)
  store i32 5, ptr %t2
  %t3 = call ptr @elem_ptr(ptr %t0, i32 1)
  store i32 1, ptr %t3
  %t4 = call ptr @elem_ptr(ptr %t0, i32 2)
  store i32 4, ptr %t4
  %t5 = call ptr @elem_ptr(ptr %t0, i32 3)
  store i32 2, ptr %t5
  %t6 = call ptr @elem_ptr(ptr %t0, i32 4)
  store i32 3, ptr %t6
  call void @bubble_sort5(ptr %t0)
  %t7 = call ptr @elem_ptr(ptr %t0, i32 0)
  %t8 = load i32, ptr %t7
  ; let first
  call void @free(ptr %t0)
  ; return
  ret i32 %t8
}

