; generated by weavec2
; source: test/performance/wir/0123_selection_sort5_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %t0 = sext i32 %index to i64
  %t1 = getelementptr i32, ptr %base, i64 %t0
  ret ptr %t1
}

; function: selection_sort5
; params: ptr
; returns: void
define void @selection_sort5(ptr %items) {
entry:
  %i.addr = alloca i32
  %min_idx.addr = alloca i32
  %j.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp slt i32 %t0, 4
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  %t2 = load i32, ptr %i.addr
  ; let min_idx
  store i32 %t2, ptr %min_idx.addr
  %t3 = load i32, ptr %i.addr
  %t4 = add i32 %t3, 1
  ; let j
  store i32 %t4, ptr %j.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %min_idx.init1 = load i32, ptr %min_idx.addr
  %j.init1 = load i32, ptr %j.addr
  br label %while.cond1
while.cond1:
  %min_idx.phi1 = phi i32 [%min_idx.init1, %while.pre1], [%min_idx.merge2, %while.latch1]
  %j.phi1 = phi i32 [%j.init1, %while.pre1], [%j.next1, %while.latch1]
  %t5 = icmp slt i32 %j.phi1, 5
  br i1 %t5, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  ; if condition
  %t6 = call ptr @elem_ptr(ptr %items, i32 %j.phi1)
  %t7 = load i32, ptr %t6
  %t8 = call ptr @elem_ptr(ptr %items, i32 %min_idx.phi1)
  %t9 = load i32, ptr %t8
  %t10 = icmp slt i32 %t7, %t9
  br i1 %t10, label %then2, label %endif2
then2:
  ; then
  ; set min_idx
  %min_idx.next120 = add i32 %j.phi1, 0
  br label %endif2
endif2:
  %min_idx.merge2 = phi i32 [%min_idx.next120, %then2], [%min_idx.phi1, %while.body1]
  ; set j
  %j.next1 = add i32 %j.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %min_idx.phi1, ptr %min_idx.addr
  store i32 %j.phi1, ptr %j.addr
  br label %while.end1
while.end1:
  %t11 = load i32, ptr %i.addr
  %t12 = call ptr @elem_ptr(ptr %items, i32 %t11)
  %t13 = load i32, ptr %t12
  ; let tmp
  %t14 = load i32, ptr %i.addr
  %t15 = call ptr @elem_ptr(ptr %items, i32 %t14)
  %t16 = load i32, ptr %min_idx.addr
  %t17 = call ptr @elem_ptr(ptr %items, i32 %t16)
  %t18 = load i32, ptr %t17
  store i32 %t18, ptr %t15
  %t19 = load i32, ptr %min_idx.addr
  %t20 = call ptr @elem_ptr(ptr %items, i32 %t19)
  store i32 %t13, ptr %t20
  ; set i
  %t21 = load i32, ptr %i.addr
  %t22 = add i32 %t21, 1
  store i32 %t22, ptr %i.addr
  br label %while.cond
while.end:
  ret void
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 20)
  ; let items
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @elem_ptr(ptr %t0, i32 0)
  store i32 9, ptr %t2
  %t3 = call ptr @elem_ptr(ptr %t0, i32 1)
  store i32 2, ptr %t3
  %t4 = call ptr @elem_ptr(ptr %t0, i32 2)
  store i32 7, ptr %t4
  %t5 = call ptr @elem_ptr(ptr %t0, i32 3)
  store i32 1, ptr %t5
  %t6 = call ptr @elem_ptr(ptr %t0, i32 4)
  store i32 5, ptr %t6
  call void @selection_sort5(ptr %t0)
  %t7 = call ptr @elem_ptr(ptr %t0, i32 2)
  %t8 = load i32, ptr %t7
  ; let mid
  call void @free(ptr %t0)
  ; return
  ret i32 %t8
}

