; generated by weavec2
; source: test/performance/wir/0128_binary_search6_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %t0 = sext i32 %index to i64
  %t1 = getelementptr i32, ptr %base, i64 %t0
  ret ptr %t1
}

; function: search6
; params: ptr, i32
; returns: i32
define i32 @search6(ptr %items, i32 %target) {
entry:
  %low.addr = alloca i32
  %high.addr = alloca i32
  %found.addr = alloca i32
  ; let low
  store i32 0, ptr %low.addr
  ; let high
  store i32 5, ptr %high.addr
  ; let found
  store i32 -1, ptr %found.addr
  ; while condition
  br label %while.pre
while.pre:
  %found.init0 = load i32, ptr %found.addr
  %low.init0 = load i32, ptr %low.addr
  %high.init0 = load i32, ptr %high.addr
  br label %while.cond
while.cond:
  %found.phi0 = phi i32 [%found.init0, %while.pre], [%found.merge1, %while.latch]
  %low.phi0 = phi i32 [%low.init0, %while.pre], [%low.merge1, %while.latch]
  %high.phi0 = phi i32 [%high.init0, %while.pre], [%high.merge1, %while.latch]
  %t0 = icmp sle i32 %low.phi0, %high.phi0
  %t1 = icmp eq i32 %found.phi0, -1
  %t2 = and i1 %t0, %t1
  br i1 %t2, label %while.body, label %while.exit-merge
while.body:
  ; while body
  %t3 = add i32 %low.phi0, %high.phi0
  %t4 = sdiv i32 %t3, 2
  ; let mid
  %t5 = call ptr @elem_ptr(ptr %items, i32 %t4)
  %t6 = load i32, ptr %t5
  ; let mid_val
  ; if condition
  %t7 = icmp eq i32 %t6, %target
  br i1 %t7, label %then1, label %else1
then1:
  ; then
  ; set found
  %t8 = add i32 %low.phi0, %high.phi0
  %found.next10 = sdiv i32 %t8, 2
  br label %endif1
else1:
  ; else
  ; if condition
  %t9 = icmp slt i32 %t6, %target
  br i1 %t9, label %then2, label %else2
then2:
  ; then
  ; set low
  %low.next20 = add i32 %t4, 1
  br label %endif2
else2:
  ; else
  ; set high
  %high.next21 = sub i32 %t4, 1
  br label %endif2
endif2:
  %low.merge2 = phi i32 [%low.next20, %then2], [%low.phi0, %else2]
  %high.merge2 = phi i32 [%high.phi0, %then2], [%high.next21, %else2]
  br label %endif1
endif1:
  %low.merge1 = phi i32 [%low.phi0, %then1], [%low.merge2, %endif2]
  %high.merge1 = phi i32 [%high.phi0, %then1], [%high.merge2, %endif2]
  %found.merge1 = phi i32 [%found.next10, %then1], [%found.phi0, %endif2]
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %found.phi0, ptr %found.addr
  store i32 %low.phi0, ptr %low.addr
  store i32 %high.phi0, ptr %high.addr
  br label %while.end
while.end:
  ; return
  %t10 = load i32, ptr %found.addr
  ret i32 %t10
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 24)
  ; let items
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 -1
endif:
  %t2 = call ptr @elem_ptr(ptr %t0, i32 0)
  store i32 2, ptr %t2
  %t3 = call ptr @elem_ptr(ptr %t0, i32 1)
  store i32 4, ptr %t3
  %t4 = call ptr @elem_ptr(ptr %t0, i32 2)
  store i32 6, ptr %t4
  %t5 = call ptr @elem_ptr(ptr %t0, i32 3)
  store i32 8, ptr %t5
  %t6 = call ptr @elem_ptr(ptr %t0, i32 4)
  store i32 10, ptr %t6
  %t7 = call ptr @elem_ptr(ptr %t0, i32 5)
  store i32 12, ptr %t7
  %t8 = call i32 @search6(ptr %t0, i32 8)
  ; let idx
  call void @free(ptr %t0)
  ; return
  ret i32 %t8
}

