; generated by weavec2
; source: test/performance/wir/0131_loop_triple_if_carried_i32.wir
; core-version: 1

; function: run
; params: none
; returns: i32
define i32 @run() {
entry:
  %a.addr = alloca i32
  %b.addr = alloca i32
  %c.addr = alloca i32
  %i.addr = alloca i32
  ; let a
  store i32 0, ptr %a.addr
  ; let b
  store i32 0, ptr %b.addr
  ; let c
  store i32 0, ptr %c.addr
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre
while.pre:
  %a.init0 = load i32, ptr %a.addr
  %b.init0 = load i32, ptr %b.addr
  %c.init0 = load i32, ptr %c.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %a.phi0 = phi i32 [%a.init0, %while.pre], [%a.merge1, %while.latch]
  %b.phi0 = phi i32 [%b.init0, %while.pre], [%b.merge1, %while.latch]
  %c.phi0 = phi i32 [%c.init0, %while.pre], [%c.merge1, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp slt i32 %i.phi0, 24
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t1 = srem i32 %i.phi0, 3
  %t2 = icmp eq i32 %t1, 0
  br i1 %t2, label %then1, label %else1
then1:
  ; then
  ; if condition
  %t3 = srem i32 %i.phi0, 6
  %t4 = icmp eq i32 %t3, 0
  br i1 %t4, label %then2, label %else2
then2:
  ; then
  ; if condition
  %t5 = srem i32 %i.phi0, 9
  %t6 = icmp eq i32 %t5, 0
  br i1 %t6, label %then3, label %else3
then3:
  ; then
  ; set a
  %a.next30 = add i32 %a.phi0, 3
  ; set b
  %b.next30 = add i32 %b.phi0, 2
  ; set c
  %c.next30 = add i32 %c.phi0, 1
  br label %endif3
else3:
  ; else
  ; set b
  %b.next31 = add i32 %b.phi0, 5
  br label %endif3
endif3:
  %a.merge3 = phi i32 [%a.next30, %then3], [%a.phi0, %else3]
  %b.merge3 = phi i32 [%b.next30, %then3], [%b.next31, %else3]
  %c.merge3 = phi i32 [%c.next30, %then3], [%c.phi0, %else3]
  br label %endif2
else2:
  ; else
  ; set c
  %c.next21 = add i32 %c.phi0, 4
  br label %endif2
endif2:
  %a.merge2 = phi i32 [%a.merge3, %endif3], [%a.phi0, %else2]
  %b.merge2 = phi i32 [%b.merge3, %endif3], [%b.phi0, %else2]
  %c.merge2 = phi i32 [%c.merge3, %endif3], [%c.next21, %else2]
  br label %endif1
else1:
  ; else
  ; if condition
  %t7 = srem i32 %i.phi0, 2
  %t8 = icmp eq i32 %t7, 0
  br i1 %t8, label %then4, label %endif4
then4:
  ; then
  ; set a
  %a.next40 = add i32 %a.phi0, 1
  br label %endif4
endif4:
  %a.merge4 = phi i32 [%a.next40, %then4], [%a.phi0, %else1]
  br label %endif1
endif1:
  %a.merge1 = phi i32 [%a.merge2, %endif2], [%a.merge4, %endif4]
  %b.merge1 = phi i32 [%b.merge2, %endif2], [%b.phi0, %endif4]
  %c.merge1 = phi i32 [%c.merge2, %endif2], [%c.phi0, %endif4]
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %a.phi0, ptr %a.addr
  store i32 %b.phi0, ptr %b.addr
  store i32 %c.phi0, ptr %c.addr
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t9 = load i32, ptr %a.addr
  %t10 = load i32, ptr %b.addr
  %t11 = add i32 %t9, %t10
  %t12 = load i32, ptr %c.addr
  %t13 = add i32 %t11, %t12
  ret i32 %t13
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @run()
  ret i32 %t0
}

