; generated by weavec2
; source: test/performance/wir/0132_matmul3x3_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: at
; params: ptr, i32, i32
; returns: ptr
define ptr @at(ptr %m, i32 %r, i32 %c) {
entry:
  ; return
  %t0 = mul i32 %r, 3
  %t1 = add i32 %t0, %c
  %t2 = sext i32 %t1 to i64
  %t3 = getelementptr i32, ptr %m, i64 %t2
  ret ptr %t3
}

; function: matmul3
; params: ptr, ptr, ptr
; returns: void
define void @matmul3(ptr %a, ptr %b, ptr %out) {
entry:
  %i.addr = alloca i32
  %j.addr = alloca i32
  %sum.addr = alloca i32
  %k.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp slt i32 %t0, 3
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let j
  store i32 0, ptr %j.addr
  ; while condition
  br label %while.cond1
while.cond1:
  %t2 = load i32, ptr %j.addr
  %t3 = icmp slt i32 %t2, 3
  br i1 %t3, label %while.body1, label %while.end1
while.body1:
  ; while body
  ; let sum
  store i32 0, ptr %sum.addr
  ; let k
  store i32 0, ptr %k.addr
  ; while condition
  br label %while.pre2
while.pre2:
  %sum.init2 = load i32, ptr %sum.addr
  %k.init2 = load i32, ptr %k.addr
  br label %while.cond2
while.cond2:
  %sum.phi2 = phi i32 [%sum.init2, %while.pre2], [%sum.next2, %while.latch2]
  %k.phi2 = phi i32 [%k.init2, %while.pre2], [%k.next2, %while.latch2]
  %t4 = icmp slt i32 %k.phi2, 3
  br i1 %t4, label %while.body2, label %while.exit-merge2
while.body2:
  ; while body
  ; set sum
  %t5 = load i32, ptr %i.addr
  %t6 = call ptr @at(ptr %a, i32 %t5, i32 %k.phi2)
  %t7 = load i32, ptr %t6
  %t8 = load i32, ptr %j.addr
  %t9 = call ptr @at(ptr %b, i32 %k.phi2, i32 %t8)
  %t10 = load i32, ptr %t9
  %t11 = mul i32 %t7, %t10
  %sum.next2 = add i32 %sum.phi2, %t11
  ; set k
  %k.next2 = add i32 %k.phi2, 1
  br label %while.latch2
while.latch2:
  br label %while.cond2
while.exit-merge2:
  ; sync loop-carried locals to stack
  store i32 %sum.phi2, ptr %sum.addr
  store i32 %k.phi2, ptr %k.addr
  br label %while.end2
while.end2:
  %t12 = load i32, ptr %i.addr
  %t13 = load i32, ptr %j.addr
  %t14 = call ptr @at(ptr %out, i32 %t12, i32 %t13)
  %t15 = load i32, ptr %sum.addr
  store i32 %t15, ptr %t14
  ; set j
  %t16 = load i32, ptr %j.addr
  %t17 = add i32 %t16, 1
  store i32 %t17, ptr %j.addr
  br label %while.cond1
while.end1:
  ; set i
  %t18 = load i32, ptr %i.addr
  %t19 = add i32 %t18, 1
  store i32 %t19, ptr %i.addr
  br label %while.cond
while.end:
  ret void
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 36)
  ; let a
  %t1 = call ptr @malloc(i64 36)
  ; let b
  %t2 = call ptr @malloc(i64 36)
  ; let out
  ; if condition
  %t3 = icmp eq ptr %t0, null
  %t4 = icmp eq ptr %t1, null
  %t5 = icmp eq ptr %t2, null
  %t6 = or i1 %t4, %t5
  %t7 = or i1 %t3, %t6
  br i1 %t7, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t8 = call ptr @at(ptr %t0, i32 0, i32 0)
  store i32 1, ptr %t8
  %t9 = call ptr @at(ptr %t0, i32 0, i32 1)
  store i32 2, ptr %t9
  %t10 = call ptr @at(ptr %t0, i32 0, i32 2)
  store i32 0, ptr %t10
  %t11 = call ptr @at(ptr %t0, i32 1, i32 0)
  store i32 0, ptr %t11
  %t12 = call ptr @at(ptr %t0, i32 1, i32 1)
  store i32 1, ptr %t12
  %t13 = call ptr @at(ptr %t0, i32 1, i32 2)
  store i32 0, ptr %t13
  %t14 = call ptr @at(ptr %t0, i32 2, i32 0)
  store i32 1, ptr %t14
  %t15 = call ptr @at(ptr %t0, i32 2, i32 1)
  store i32 1, ptr %t15
  %t16 = call ptr @at(ptr %t0, i32 2, i32 2)
  store i32 1, ptr %t16
  %t17 = call ptr @at(ptr %t1, i32 0, i32 0)
  store i32 1, ptr %t17
  %t18 = call ptr @at(ptr %t1, i32 0, i32 1)
  store i32 0, ptr %t18
  %t19 = call ptr @at(ptr %t1, i32 0, i32 2)
  store i32 0, ptr %t19
  %t20 = call ptr @at(ptr %t1, i32 1, i32 0)
  store i32 0, ptr %t20
  %t21 = call ptr @at(ptr %t1, i32 1, i32 1)
  store i32 1, ptr %t21
  %t22 = call ptr @at(ptr %t1, i32 1, i32 2)
  store i32 0, ptr %t22
  %t23 = call ptr @at(ptr %t1, i32 2, i32 0)
  store i32 0, ptr %t23
  %t24 = call ptr @at(ptr %t1, i32 2, i32 1)
  store i32 0, ptr %t24
  %t25 = call ptr @at(ptr %t1, i32 2, i32 2)
  store i32 1, ptr %t25
  call void @matmul3(ptr %t0, ptr %t1, ptr %t2)
  %t26 = call ptr @at(ptr %t2, i32 2, i32 2)
  %t27 = load i32, ptr %t26
  ; let ans
  call void @free(ptr %t0)
  call void @free(ptr %t1)
  call void @free(ptr %t2)
  ; return
  ret i32 %t27
}

