; generated by weavec2
; source: test/performance/wir/0134_floyd_warshall4_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: at
; params: ptr, i32, i32
; returns: ptr
define ptr @at(ptr %dist, i32 %i, i32 %j) {
entry:
  ; return
  %t0 = mul i32 %i, 4
  %t1 = add i32 %t0, %j
  %t2 = sext i32 %t1 to i64
  %t3 = getelementptr i32, ptr %dist, i64 %t2
  ret ptr %t3
}

; function: floyd4
; params: ptr
; returns: void
define void @floyd4(ptr %dist) {
entry:
  %k.addr = alloca i32
  %i.addr = alloca i32
  %j.addr = alloca i32
  ; let k
  store i32 0, ptr %k.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %k.addr
  %t1 = icmp slt i32 %t0, 4
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond1
while.cond1:
  %t2 = load i32, ptr %i.addr
  %t3 = icmp slt i32 %t2, 4
  br i1 %t3, label %while.body1, label %while.end1
while.body1:
  ; while body
  ; let j
  store i32 0, ptr %j.addr
  ; while condition
  br label %while.pre2
while.pre2:
  %j.init2 = load i32, ptr %j.addr
  br label %while.cond2
while.cond2:
  %j.phi2 = phi i32 [%j.init2, %while.pre2], [%j.next2, %while.latch2]
  %t4 = icmp slt i32 %j.phi2, 4
  br i1 %t4, label %while.body2, label %while.exit-merge2
while.body2:
  ; while body
  %t5 = load i32, ptr %i.addr
  %t6 = load i32, ptr %k.addr
  %t7 = call ptr @at(ptr %dist, i32 %t5, i32 %t6)
  %t8 = load i32, ptr %t7
  %t9 = load i32, ptr %k.addr
  %t10 = call ptr @at(ptr %dist, i32 %t9, i32 %j.phi2)
  %t11 = load i32, ptr %t10
  %t12 = add i32 %t8, %t11
  ; let via
  %t13 = load i32, ptr %i.addr
  %t14 = call ptr @at(ptr %dist, i32 %t13, i32 %j.phi2)
  %t15 = load i32, ptr %t14
  ; let cur
  ; if condition
  %t16 = icmp slt i32 %t12, %t15
  br i1 %t16, label %then3, label %endif3
then3:
  ; then
  %t17 = load i32, ptr %i.addr
  %t18 = call ptr @at(ptr %dist, i32 %t17, i32 %j.phi2)
  store i32 %t12, ptr %t18
  br label %endif3
endif3:
  ; set j
  %j.next2 = add i32 %j.phi2, 1
  br label %while.latch2
while.latch2:
  br label %while.cond2
while.exit-merge2:
  ; sync loop-carried locals to stack
  store i32 %j.phi2, ptr %j.addr
  br label %while.end2
while.end2:
  ; set i
  %t19 = load i32, ptr %i.addr
  %t20 = add i32 %t19, 1
  store i32 %t20, ptr %i.addr
  br label %while.cond1
while.end1:
  ; set k
  %t21 = load i32, ptr %k.addr
  %t22 = add i32 %t21, 1
  store i32 %t22, ptr %k.addr
  br label %while.cond
while.end:
  ret void
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 64)
  ; let dist
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @at(ptr %t0, i32 0, i32 0)
  store i32 0, ptr %t2
  %t3 = call ptr @at(ptr %t0, i32 0, i32 1)
  store i32 5, ptr %t3
  %t4 = call ptr @at(ptr %t0, i32 0, i32 2)
  store i32 9999, ptr %t4
  %t5 = call ptr @at(ptr %t0, i32 0, i32 3)
  store i32 9999, ptr %t5
  %t6 = call ptr @at(ptr %t0, i32 1, i32 0)
  store i32 9999, ptr %t6
  %t7 = call ptr @at(ptr %t0, i32 1, i32 1)
  store i32 0, ptr %t7
  %t8 = call ptr @at(ptr %t0, i32 1, i32 2)
  store i32 1, ptr %t8
  %t9 = call ptr @at(ptr %t0, i32 1, i32 3)
  store i32 9999, ptr %t9
  %t10 = call ptr @at(ptr %t0, i32 2, i32 0)
  store i32 9999, ptr %t10
  %t11 = call ptr @at(ptr %t0, i32 2, i32 1)
  store i32 9999, ptr %t11
  %t12 = call ptr @at(ptr %t0, i32 2, i32 2)
  store i32 0, ptr %t12
  %t13 = call ptr @at(ptr %t0, i32 2, i32 3)
  store i32 2, ptr %t13
  %t14 = call ptr @at(ptr %t0, i32 3, i32 0)
  store i32 9999, ptr %t14
  %t15 = call ptr @at(ptr %t0, i32 3, i32 1)
  store i32 9999, ptr %t15
  %t16 = call ptr @at(ptr %t0, i32 3, i32 2)
  store i32 9999, ptr %t16
  %t17 = call ptr @at(ptr %t0, i32 3, i32 3)
  store i32 0, ptr %t17
  call void @floyd4(ptr %t0)
  %t18 = call ptr @at(ptr %t0, i32 0, i32 3)
  %t19 = load i32, ptr %t18
  ; let ans
  call void @free(ptr %t0)
  ; return
  ret i32 %t19
}

