; generated by weavec2
; source: test/performance/wir/0136_knapsack01_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: dp_at
; params: ptr, i32, i32
; returns: ptr
define ptr @dp_at(ptr %dp, i32 %i, i32 %w) {
entry:
  ; return
  %t0 = mul i32 %i, 12
  %t1 = add i32 %t0, %w
  %t2 = sext i32 %t1 to i64
  %t3 = getelementptr i32, ptr %dp, i64 %t2
  ret ptr %t3
}

; function: weight_of
; params: i32
; returns: i32
define i32 @weight_of(i32 %item) {
entry:
  ; if condition
  %t0 = icmp eq i32 %item, 0
  br i1 %t0, label %then, label %endif
then:
  ; then
  ; return
  ret i32 2
endif:
  ; if condition
  %t1 = icmp eq i32 %item, 1
  br i1 %t1, label %then1, label %endif1
then1:
  ; then
  ; return
  ret i32 3
endif1:
  ; if condition
  %t2 = icmp eq i32 %item, 2
  br i1 %t2, label %then2, label %endif2
then2:
  ; then
  ; return
  ret i32 4
endif2:
  ; if condition
  %t3 = icmp eq i32 %item, 3
  br i1 %t3, label %then3, label %endif3
then3:
  ; then
  ; return
  ret i32 5
endif3:
  ; return
  ret i32 9
}

; function: value_of
; params: i32
; returns: i32
define i32 @value_of(i32 %item) {
entry:
  ; if condition
  %t0 = icmp eq i32 %item, 0
  br i1 %t0, label %then, label %endif
then:
  ; then
  ; return
  ret i32 3
endif:
  ; if condition
  %t1 = icmp eq i32 %item, 1
  br i1 %t1, label %then1, label %endif1
then1:
  ; then
  ; return
  ret i32 4
endif1:
  ; if condition
  %t2 = icmp eq i32 %item, 2
  br i1 %t2, label %then2, label %endif2
then2:
  ; then
  ; return
  ret i32 5
endif2:
  ; if condition
  %t3 = icmp eq i32 %item, 3
  br i1 %t3, label %then3, label %endif3
then3:
  ; then
  ; return
  ret i32 7
endif3:
  ; return
  ret i32 10
}

; function: knapsack5
; params: ptr
; returns: i32
define i32 @knapsack5(ptr %dp) {
entry:
  %i.addr = alloca i32
  %w.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp sle i32 %t0, 5
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let w
  store i32 0, ptr %w.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %w.init1 = load i32, ptr %w.addr
  br label %while.cond1
while.cond1:
  %w.phi1 = phi i32 [%w.init1, %while.pre1], [%w.next1, %while.latch1]
  %t2 = icmp sle i32 %w.phi1, 11
  br i1 %t2, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  ; if condition
  %t3 = load i32, ptr %i.addr
  %t4 = icmp eq i32 %t3, 0
  br i1 %t4, label %then2, label %else2
then2:
  ; then
  %t5 = load i32, ptr %i.addr
  %t6 = call ptr @dp_at(ptr %dp, i32 %t5, i32 %w.phi1)
  store i32 0, ptr %t6
  br label %endif2
else2:
  ; else
  %t7 = load i32, ptr %i.addr
  %t8 = sub i32 %t7, 1
  %t9 = call i32 @weight_of(i32 %t8)
  ; let wt
  %t10 = load i32, ptr %i.addr
  %t11 = sub i32 %t10, 1
  %t12 = call ptr @dp_at(ptr %dp, i32 %t11, i32 %w.phi1)
  %t13 = load i32, ptr %t12
  ; let skip
  ; let take
  ; if condition
  %t14 = icmp sge i32 %w.phi1, %t9
  br i1 %t14, label %then3, label %endif3
then3:
  ; then
  %t15 = load i32, ptr %i.addr
  %t16 = sub i32 %t15, 1
  %t17 = call i32 @value_of(i32 %t16)
  %t18 = load i32, ptr %i.addr
  %t19 = sub i32 %t18, 1
  %t20 = sub i32 %w.phi1, %t9
  %t21 = call ptr @dp_at(ptr %dp, i32 %t19, i32 %t20)
  %t22 = load i32, ptr %t21
  %t23 = add i32 %t17, %t22
  ; let take
  br label %endif3
endif3:
  ; if condition
  %t24 = icmp sgt i32 0, %t13
  br i1 %t24, label %then4, label %else4
then4:
  ; then
  %t25 = load i32, ptr %i.addr
  %t26 = call ptr @dp_at(ptr %dp, i32 %t25, i32 %w.phi1)
  store i32 0, ptr %t26
  br label %endif4
else4:
  ; else
  %t27 = load i32, ptr %i.addr
  %t28 = call ptr @dp_at(ptr %dp, i32 %t27, i32 %w.phi1)
  store i32 %t13, ptr %t28
  br label %endif4
endif4:
  br label %endif2
endif2:
  ; set w
  %w.next1 = add i32 %w.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %w.phi1, ptr %w.addr
  br label %while.end1
while.end1:
  ; set i
  %t29 = load i32, ptr %i.addr
  %t30 = add i32 %t29, 1
  store i32 %t30, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t31 = call ptr @dp_at(ptr %dp, i32 5, i32 11)
  %t32 = load i32, ptr %t31
  ret i32 %t32
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 288)
  ; let dp
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call i32 @knapsack5(ptr %t0)
  ; let best
  call void @free(ptr %t0)
  ; return
  ret i32 %t2
}

