; generated by weavec2
; source: test/performance/wir/0138_mod_div_nested_accum_i32.wir
; core-version: 1

; function: run
; params: none
; returns: i32
define i32 @run() {
entry:
  %i.addr = alloca i32
  %acc.addr = alloca i32
  ; let i
  store i32 1, ptr %i.addr
  ; let acc
  store i32 0, ptr %acc.addr
  ; while condition
  br label %while.pre
while.pre:
  %acc.init0 = load i32, ptr %acc.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %acc.phi0 = phi i32 [%acc.init0, %while.pre], [%acc.merge1, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp sle i32 %i.phi0, 200
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  %t1 = srem i32 %i.phi0, 7
  ; let r7
  %t2 = sdiv i32 %i.phi0, 7
  ; let q7
  %t3 = srem i32 %i.phi0, 13
  ; let r13
  ; if condition
  %t4 = icmp eq i32 %t1, 0
  br i1 %t4, label %then1, label %else1
then1:
  ; then
  ; set acc
  %acc.next10 = add i32 %acc.phi0, %t2
  br label %endif1
else1:
  ; else
  ; if condition
  %t5 = icmp eq i32 %t3, 0
  br i1 %t5, label %then2, label %else2
then2:
  ; then
  ; set acc
  %acc.next20 = sub i32 %acc.phi0, %t1
  br label %endif2
else2:
  ; else
  ; set acc
  %t6 = add i32 %t1, %t3
  %acc.next21 = add i32 %acc.phi0, %t6
  br label %endif2
endif2:
  %acc.merge2 = phi i32 [%acc.next20, %then2], [%acc.next21, %else2]
  br label %endif1
endif1:
  %acc.merge1 = phi i32 [%acc.next10, %then1], [%acc.merge2, %endif2]
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %acc.phi0, ptr %acc.addr
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t7 = load i32, ptr %acc.addr
  ret i32 %t7
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @run()
  ret i32 %t0
}

