; generated by weavec2
; source: test/performance/wir/0141_lcs_table_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: at
; params: ptr, i32, i32
; returns: ptr
define ptr @at(ptr %t, i32 %i, i32 %j) {
entry:
  ; return
  %t0 = mul i32 %i, 9
  %t1 = add i32 %t0, %j
  %t2 = sext i32 %t1 to i64
  %t3 = getelementptr i32, ptr %t, i64 %t2
  ret ptr %t3
}

; function: lcs8
; params: ptr
; returns: i32
define i32 @lcs8(ptr %t) {
entry:
  %i.addr = alloca i32
  %j.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp sle i32 %t0, 8
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let j
  store i32 0, ptr %j.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %j.init1 = load i32, ptr %j.addr
  br label %while.cond1
while.cond1:
  %j.phi1 = phi i32 [%j.init1, %while.pre1], [%j.next1, %while.latch1]
  %t2 = icmp sle i32 %j.phi1, 8
  br i1 %t2, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  ; if condition
  %t3 = load i32, ptr %i.addr
  %t4 = icmp eq i32 %t3, 0
  %t5 = icmp eq i32 %j.phi1, 0
  %t6 = or i1 %t4, %t5
  br i1 %t6, label %then2, label %else2
then2:
  ; then
  %t7 = load i32, ptr %i.addr
  %t8 = call ptr @at(ptr %t, i32 %t7, i32 %j.phi1)
  store i32 0, ptr %t8
  br label %endif2
else2:
  ; else
  %t9 = load i32, ptr %i.addr
  %t10 = sub i32 %t9, 1
  %t11 = call ptr @at(ptr %t, i32 %t10, i32 %j.phi1)
  %t12 = load i32, ptr %t11
  ; let up
  %t13 = load i32, ptr %i.addr
  %t14 = sub i32 %j.phi1, 1
  %t15 = call ptr @at(ptr %t, i32 %t13, i32 %t14)
  %t16 = load i32, ptr %t15
  ; let left
  %t17 = load i32, ptr %i.addr
  %t18 = sub i32 %t17, 1
  %t19 = sub i32 %j.phi1, 1
  %t20 = call ptr @at(ptr %t, i32 %t18, i32 %t19)
  %t21 = load i32, ptr %t20
  ; let diag
  %t22 = add i32 %t21, 1
  ; let cand
  ; if condition
  %t23 = icmp sgt i32 %t22, %t12
  br i1 %t23, label %then3, label %else3
then3:
  ; then
  ; if condition
  %t24 = icmp sgt i32 %t22, %t16
  br i1 %t24, label %then4, label %else4
then4:
  ; then
  %t25 = load i32, ptr %i.addr
  %t26 = call ptr @at(ptr %t, i32 %t25, i32 %j.phi1)
  store i32 %t22, ptr %t26
  br label %endif4
else4:
  ; else
  %t27 = load i32, ptr %i.addr
  %t28 = call ptr @at(ptr %t, i32 %t27, i32 %j.phi1)
  store i32 %t16, ptr %t28
  br label %endif4
endif4:
  br label %endif3
else3:
  ; else
  ; if condition
  %t29 = icmp sgt i32 %t16, %t12
  br i1 %t29, label %then5, label %else5
then5:
  ; then
  %t30 = load i32, ptr %i.addr
  %t31 = call ptr @at(ptr %t, i32 %t30, i32 %j.phi1)
  store i32 %t16, ptr %t31
  br label %endif5
else5:
  ; else
  %t32 = load i32, ptr %i.addr
  %t33 = call ptr @at(ptr %t, i32 %t32, i32 %j.phi1)
  store i32 %t12, ptr %t33
  br label %endif5
endif5:
  br label %endif3
endif3:
  br label %endif2
endif2:
  ; set j
  %j.next1 = add i32 %j.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %j.phi1, ptr %j.addr
  br label %while.end1
while.end1:
  ; set i
  %t34 = load i32, ptr %i.addr
  %t35 = add i32 %t34, 1
  store i32 %t35, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t36 = call ptr @at(ptr %t, i32 8, i32 8)
  %t37 = load i32, ptr %t36
  ret i32 %t37
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 324)
  ; let t
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call i32 @lcs8(ptr %t0)
  ; let ans
  call void @free(ptr %t0)
  ; return
  ret i32 %t2
}

