; generated by weavec2
; source: test/performance/wir/0143_rolling_hash_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: hash64
; params: ptr
; returns: i32
define i32 @hash64(ptr %data) {
entry:
  %h.addr = alloca i32
  %i.addr = alloca i32
  ; let h
  store i32 0, ptr %h.addr
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre
while.pre:
  %h.init0 = load i32, ptr %h.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %h.phi0 = phi i32 [%h.init0, %while.pre], [%h.next0, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp slt i32 %i.phi0, 64
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  %t1 = sext i32 %i.phi0 to i64
  %t2 = getelementptr i32, ptr %data, i64 %t1
  %t3 = load i32, ptr %t2
  ; let b
  ; set h
  %t4 = mul i32 %h.phi0, 31
  %t5 = add i32 %t4, %t3
  %t6 = add i32 %t5, 1
  %h.next0 = srem i32 %t6, 1000003
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %h.phi0, ptr %h.addr
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t7 = load i32, ptr %h.addr
  ret i32 %t7
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %k.addr = alloca i32
  %t0 = call ptr @malloc(i64 256)
  ; let data
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  ; let k
  store i32 0, ptr %k.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %k.init1 = load i32, ptr %k.addr
  br label %while.cond1
while.cond1:
  %k.phi1 = phi i32 [%k.init1, %while.pre1], [%k.next1, %while.latch1]
  %t2 = icmp slt i32 %k.phi1, 64
  br i1 %t2, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  %t3 = sext i32 %k.phi1 to i64
  %t4 = getelementptr i32, ptr %t0, i64 %t3
  %t5 = mul i32 %k.phi1, 7
  %t6 = add i32 %t5, 13
  store i32 %t6, ptr %t4
  ; set k
  %k.next1 = add i32 %k.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %k.phi1, ptr %k.addr
  br label %while.end1
while.end1:
  %t7 = call i32 @hash64(ptr %t0)
  ; let ans
  call void @free(ptr %t0)
  ; return
  ret i32 %t7
}

