; generated by weavec2
; source: test/performance/wir/0144_matmul4x4_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: at
; params: ptr, i32, i32
; returns: ptr
define ptr @at(ptr %m, i32 %r, i32 %c) {
entry:
  ; return
  %t0 = mul i32 %r, 4
  %t1 = add i32 %t0, %c
  %t2 = sext i32 %t1 to i64
  %t3 = getelementptr i32, ptr %m, i64 %t2
  ret ptr %t3
}

; function: matmul4
; params: ptr, ptr, ptr
; returns: void
define void @matmul4(ptr %a, ptr %b, ptr %out) {
entry:
  %i.addr = alloca i32
  %j.addr = alloca i32
  %sum.addr = alloca i32
  %k.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp slt i32 %t0, 4
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let j
  store i32 0, ptr %j.addr
  ; while condition
  br label %while.cond1
while.cond1:
  %t2 = load i32, ptr %j.addr
  %t3 = icmp slt i32 %t2, 4
  br i1 %t3, label %while.body1, label %while.end1
while.body1:
  ; while body
  ; let sum
  store i32 0, ptr %sum.addr
  ; let k
  store i32 0, ptr %k.addr
  ; while condition
  br label %while.pre2
while.pre2:
  %sum.init2 = load i32, ptr %sum.addr
  %k.init2 = load i32, ptr %k.addr
  br label %while.cond2
while.cond2:
  %sum.phi2 = phi i32 [%sum.init2, %while.pre2], [%sum.next2, %while.latch2]
  %k.phi2 = phi i32 [%k.init2, %while.pre2], [%k.next2, %while.latch2]
  %t4 = icmp slt i32 %k.phi2, 4
  br i1 %t4, label %while.body2, label %while.exit-merge2
while.body2:
  ; while body
  ; set sum
  %t5 = load i32, ptr %i.addr
  %t6 = call ptr @at(ptr %a, i32 %t5, i32 %k.phi2)
  %t7 = load i32, ptr %t6
  %t8 = load i32, ptr %j.addr
  %t9 = call ptr @at(ptr %b, i32 %k.phi2, i32 %t8)
  %t10 = load i32, ptr %t9
  %t11 = mul i32 %t7, %t10
  %sum.next2 = add i32 %sum.phi2, %t11
  ; set k
  %k.next2 = add i32 %k.phi2, 1
  br label %while.latch2
while.latch2:
  br label %while.cond2
while.exit-merge2:
  ; sync loop-carried locals to stack
  store i32 %sum.phi2, ptr %sum.addr
  store i32 %k.phi2, ptr %k.addr
  br label %while.end2
while.end2:
  %t12 = load i32, ptr %i.addr
  %t13 = load i32, ptr %j.addr
  %t14 = call ptr @at(ptr %out, i32 %t12, i32 %t13)
  %t15 = load i32, ptr %sum.addr
  store i32 %t15, ptr %t14
  ; set j
  %t16 = load i32, ptr %j.addr
  %t17 = add i32 %t16, 1
  store i32 %t17, ptr %j.addr
  br label %while.cond1
while.end1:
  ; set i
  %t18 = load i32, ptr %i.addr
  %t19 = add i32 %t18, 1
  store i32 %t19, ptr %i.addr
  br label %while.cond
while.end:
  ret void
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %n.addr = alloca i32
  %t0 = call ptr @malloc(i64 64)
  ; let a
  %t1 = call ptr @malloc(i64 64)
  ; let b
  %t2 = call ptr @malloc(i64 64)
  ; let out
  ; if condition
  %t3 = icmp eq ptr %t0, null
  %t4 = icmp eq ptr %t1, null
  %t5 = icmp eq ptr %t2, null
  %t6 = or i1 %t4, %t5
  %t7 = or i1 %t3, %t6
  br i1 %t7, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  ; let n
  store i32 0, ptr %n.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %n.init1 = load i32, ptr %n.addr
  br label %while.cond1
while.cond1:
  %n.phi1 = phi i32 [%n.init1, %while.pre1], [%n.next1, %while.latch1]
  %t8 = icmp slt i32 %n.phi1, 16
  br i1 %t8, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  %t9 = sext i32 %n.phi1 to i64
  %t10 = getelementptr i32, ptr %t0, i64 %t9
  %t11 = add i32 %n.phi1, 1
  store i32 %t11, ptr %t10
  %t12 = sext i32 %n.phi1 to i64
  %t13 = getelementptr i32, ptr %t1, i64 %t12
  %t14 = add i32 %n.phi1, 2
  %t15 = srem i32 %t14, 4
  store i32 %t15, ptr %t13
  ; set n
  %n.next1 = add i32 %n.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %n.phi1, ptr %n.addr
  br label %while.end1
while.end1:
  call void @matmul4(ptr %t0, ptr %t1, ptr %t2)
  %t16 = call ptr @at(ptr %t2, i32 3, i32 3)
  %t17 = load i32, ptr %t16
  ; let ans
  call void @free(ptr %t0)
  call void @free(ptr %t1)
  call void @free(ptr %t2)
  ; return
  ret i32 %t17
}

