; generated by weavec2
; source: test/performance/wir/0145_insertion_sort10_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: elem
; params: ptr, i32
; returns: ptr
define ptr @elem(ptr %a, i32 %idx) {
entry:
  ; return
  %t0 = sext i32 %idx to i64
  %t1 = getelementptr i32, ptr %a, i64 %t0
  ret ptr %t1
}

; function: insertion_sort10
; params: ptr
; returns: void
define void @insertion_sort10(ptr %a) {
entry:
  %i.addr = alloca i32
  %j.addr = alloca i32
  ; let i
  store i32 1, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp slt i32 %t0, 10
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  %t2 = load i32, ptr %i.addr
  %t3 = call ptr @elem(ptr %a, i32 %t2)
  %t4 = load i32, ptr %t3
  ; let key
  %t5 = load i32, ptr %i.addr
  %t6 = sub i32 %t5, 1
  ; let j
  store i32 %t6, ptr %j.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %j.init1 = load i32, ptr %j.addr
  br label %while.cond1
while.cond1:
  %j.phi1 = phi i32 [%j.init1, %while.pre1], [%j.next1, %while.latch1]
  %t7 = icmp sge i32 %j.phi1, 0
  %t8 = call ptr @elem(ptr %a, i32 %j.phi1)
  %t9 = load i32, ptr %t8
  %t10 = icmp sgt i32 %t9, %t4
  %t11 = and i1 %t7, %t10
  br i1 %t11, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  %t12 = add i32 %j.phi1, 1
  %t13 = call ptr @elem(ptr %a, i32 %t12)
  %t14 = call ptr @elem(ptr %a, i32 %j.phi1)
  %t15 = load i32, ptr %t14
  store i32 %t15, ptr %t13
  ; set j
  %j.next1 = sub i32 %j.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %j.phi1, ptr %j.addr
  br label %while.end1
while.end1:
  %t16 = load i32, ptr %j.addr
  %t17 = add i32 %t16, 1
  %t18 = call ptr @elem(ptr %a, i32 %t17)
  store i32 %t4, ptr %t18
  ; set i
  %t19 = load i32, ptr %i.addr
  %t20 = add i32 %t19, 1
  store i32 %t20, ptr %i.addr
  br label %while.cond
while.end:
  ret void
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 40)
  ; let a
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @elem(ptr %t0, i32 0)
  store i32 10, ptr %t2
  %t3 = call ptr @elem(ptr %t0, i32 1)
  store i32 3, ptr %t3
  %t4 = call ptr @elem(ptr %t0, i32 2)
  store i32 8, ptr %t4
  %t5 = call ptr @elem(ptr %t0, i32 3)
  store i32 1, ptr %t5
  %t6 = call ptr @elem(ptr %t0, i32 4)
  store i32 9, ptr %t6
  %t7 = call ptr @elem(ptr %t0, i32 5)
  store i32 2, ptr %t7
  %t8 = call ptr @elem(ptr %t0, i32 6)
  store i32 7, ptr %t8
  %t9 = call ptr @elem(ptr %t0, i32 7)
  store i32 4, ptr %t9
  %t10 = call ptr @elem(ptr %t0, i32 8)
  store i32 6, ptr %t10
  %t11 = call ptr @elem(ptr %t0, i32 9)
  store i32 5, ptr %t11
  call void @insertion_sort10(ptr %t0)
  %t12 = call ptr @elem(ptr %t0, i32 0)
  %t13 = load i32, ptr %t12
  ; let first
  call void @free(ptr %t0)
  ; return
  ret i32 %t13
}

