; generated by weavec2
; source: test/performance/wir/0148_gcd_batch_i32.wir
; core-version: 1

; function: gcd_pair
; params: i32, i32
; returns: i32
define i32 @gcd_pair(i32 %a, i32 %b) {
entry:
  %x.addr = alloca i32
  %y.addr = alloca i32
  ; let x
  store i32 %a, ptr %x.addr
  ; let y
  store i32 %b, ptr %y.addr
  ; while condition
  br label %while.pre
while.pre:
  %x.init0 = load i32, ptr %x.addr
  %y.init0 = load i32, ptr %y.addr
  br label %while.cond
while.cond:
  %x.phi0 = phi i32 [%x.init0, %while.pre], [%y.phi0, %while.latch]
  %y.phi0 = phi i32 [%y.init0, %while.pre], [%y.next0, %while.latch]
  %t0 = icmp ne i32 %y.phi0, 0
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  %t1 = srem i32 %x.phi0, %y.phi0
  ; let r
  ; set x
  ; set y
  %y.next0 = add i32 %t1, 0
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %x.phi0, ptr %x.addr
  store i32 %y.phi0, ptr %y.addr
  br label %while.end
while.end:
  ; return
  %t2 = load i32, ptr %x.addr
  ret i32 %t2
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %k.addr = alloca i32
  %acc.addr = alloca i32
  ; let k
  store i32 0, ptr %k.addr
  ; let acc
  store i32 0, ptr %acc.addr
  ; while condition
  br label %while.pre
while.pre:
  %acc.init0 = load i32, ptr %acc.addr
  %k.init0 = load i32, ptr %k.addr
  br label %while.cond
while.cond:
  %acc.phi0 = phi i32 [%acc.init0, %while.pre], [%acc.next0, %while.latch]
  %k.phi0 = phi i32 [%k.init0, %while.pre], [%k.next0, %while.latch]
  %t0 = icmp slt i32 %k.phi0, 12
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  %t1 = mul i32 %k.phi0, 37
  %t2 = add i32 %t1, 100
  ; let a
  %t3 = mul i32 %k.phi0, 53
  %t4 = add i32 %t3, 200
  ; let b
  %t5 = call i32 @gcd_pair(i32 %t2, i32 %t4)
  ; let g
  ; set acc
  %acc.next0 = add i32 %acc.phi0, %t5
  ; set k
  %k.next0 = add i32 %k.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %acc.phi0, ptr %acc.addr
  store i32 %k.phi0, ptr %k.addr
  br label %while.end
while.end:
  ; return
  %t6 = load i32, ptr %acc.addr
  ret i32 %t6
}

