; generated by weavec2
; source: test/performance/wir/0150_edit_distance6_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: at
; params: ptr, i32, i32
; returns: ptr
define ptr @at(ptr %t, i32 %i, i32 %j) {
entry:
  ; return
  %t0 = mul i32 %i, 7
  %t1 = add i32 %t0, %j
  %t2 = sext i32 %t1 to i64
  %t3 = getelementptr i32, ptr %t, i64 %t2
  ret ptr %t3
}

; function: cost
; params: i32, i32
; returns: i32
define i32 @cost(i32 %i, i32 %j) {
entry:
  ; if condition
  %t0 = add i32 %i, %j
  %t1 = srem i32 %t0, 3
  %t2 = icmp eq i32 %t1, 0
  br i1 %t2, label %then, label %else
then:
  ; then
  ; return
  ret i32 0
else:
  ; else
  ; return
  ret i32 1
}

; function: edit6
; params: ptr
; returns: i32
define i32 @edit6(ptr %t) {
entry:
  %i.addr = alloca i32
  %j.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp sle i32 %t0, 6
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let j
  store i32 0, ptr %j.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %j.init1 = load i32, ptr %j.addr
  br label %while.cond1
while.cond1:
  %j.phi1 = phi i32 [%j.init1, %while.pre1], [%j.next1, %while.latch1]
  %t2 = icmp sle i32 %j.phi1, 6
  br i1 %t2, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  ; if condition
  %t3 = load i32, ptr %i.addr
  %t4 = icmp eq i32 %t3, 0
  %t5 = icmp eq i32 %j.phi1, 0
  %t6 = or i1 %t4, %t5
  br i1 %t6, label %then2, label %else2
then2:
  ; then
  %t7 = load i32, ptr %i.addr
  %t8 = call ptr @at(ptr %t, i32 %t7, i32 %j.phi1)
  %t9 = load i32, ptr %i.addr
  %t10 = add i32 %t9, %j.phi1
  store i32 %t10, ptr %t8
  br label %endif2
else2:
  ; else
  %t11 = load i32, ptr %i.addr
  %t12 = sub i32 %t11, 1
  %t13 = call ptr @at(ptr %t, i32 %t12, i32 %j.phi1)
  %t14 = load i32, ptr %t13
  %t15 = add i32 %t14, 1
  ; let del
  %t16 = load i32, ptr %i.addr
  %t17 = sub i32 %j.phi1, 1
  %t18 = call ptr @at(ptr %t, i32 %t16, i32 %t17)
  %t19 = load i32, ptr %t18
  %t20 = add i32 %t19, 1
  ; let ins
  %t21 = load i32, ptr %i.addr
  %t22 = call i32 @cost(i32 %t21, i32 %j.phi1)
  ; let sub_cost
  %t23 = load i32, ptr %i.addr
  %t24 = sub i32 %t23, 1
  %t25 = sub i32 %j.phi1, 1
  %t26 = call ptr @at(ptr %t, i32 %t24, i32 %t25)
  %t27 = load i32, ptr %t26
  %t28 = add i32 %t27, %t22
  %t29 = add i32 %t28, 0
  ; let rep
  ; let best
  ; if condition
  %t30 = icmp sgt i32 %t20, %t15
  br i1 %t30, label %then3, label %else3
then3:
  ; then
  ; let best
  br label %endif3
else3:
  ; else
  ; if condition
  %t31 = icmp sgt i32 %t29, %t15
  br i1 %t31, label %then4, label %endif4
then4:
  ; then
  ; let best
  br label %endif4
endif4:
  br label %endif3
endif3:
  %t32 = load i32, ptr %i.addr
  %t33 = call ptr @at(ptr %t, i32 %t32, i32 %j.phi1)
  store i32 %t15, ptr %t33
  br label %endif2
endif2:
  ; set j
  %j.next1 = add i32 %j.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %j.phi1, ptr %j.addr
  br label %while.end1
while.end1:
  ; set i
  %t34 = load i32, ptr %i.addr
  %t35 = add i32 %t34, 1
  store i32 %t35, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t36 = call ptr @at(ptr %t, i32 6, i32 6)
  %t37 = load i32, ptr %t36
  ret i32 %t37
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 196)
  ; let t
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call i32 @edit6(ptr %t0)
  ; let dist
  call void @free(ptr %t0)
  ; return
  ret i32 %t2
}

