; generated by weavec2
; source: test/performance/wir/0151_counting_sort12_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: elem
; params: ptr, i32
; returns: ptr
define ptr @elem(ptr %a, i32 %idx) {
entry:
  ; return
  %t0 = sext i32 %idx to i64
  %t1 = getelementptr i32, ptr %a, i64 %t0
  ret ptr %t1
}

; function: counting_sort12
; params: ptr, ptr
; returns: i32
define i32 @counting_sort12(ptr %src, ptr %dst) {
entry:
  %z.addr = alloca i32
  %i.addr = alloca i32
  %total.addr = alloca i32
  %k.addr = alloca i32
  %j.addr = alloca i32
  %t0 = call ptr @malloc(i64 24)
  ; let cnt
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  ; let z
  store i32 0, ptr %z.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %z.init1 = load i32, ptr %z.addr
  br label %while.cond1
while.cond1:
  %z.phi1 = phi i32 [%z.init1, %while.pre1], [%z.next1, %while.latch1]
  %t2 = icmp slt i32 %z.phi1, 6
  br i1 %t2, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  %t3 = call ptr @elem(ptr %t0, i32 %z.phi1)
  store i32 0, ptr %t3
  ; set z
  %z.next1 = add i32 %z.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %z.phi1, ptr %z.addr
  br label %while.end1
while.end1:
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre2
while.pre2:
  %i.init2 = load i32, ptr %i.addr
  br label %while.cond2
while.cond2:
  %i.phi2 = phi i32 [%i.init2, %while.pre2], [%i.next2, %while.latch2]
  %t4 = icmp slt i32 %i.phi2, 12
  br i1 %t4, label %while.body2, label %while.exit-merge2
while.body2:
  ; while body
  %t5 = call ptr @elem(ptr %src, i32 %i.phi2)
  %t6 = load i32, ptr %t5
  ; let v
  %t7 = call ptr @elem(ptr %t0, i32 %t6)
  ; let cptr
  %t8 = load i32, ptr %t7
  %t9 = add i32 %t8, 1
  store i32 %t9, ptr %t7
  ; set i
  %i.next2 = add i32 %i.phi2, 1
  br label %while.latch2
while.latch2:
  br label %while.cond2
while.exit-merge2:
  ; sync loop-carried locals to stack
  store i32 %i.phi2, ptr %i.addr
  br label %while.end2
while.end2:
  ; let total
  store i32 0, ptr %total.addr
  ; let k
  store i32 1, ptr %k.addr
  ; while condition
  br label %while.pre3
while.pre3:
  %k.init3 = load i32, ptr %k.addr
  br label %while.cond3
while.cond3:
  %k.phi3 = phi i32 [%k.init3, %while.pre3], [%k.next3, %while.latch3]
  %t10 = icmp slt i32 %k.phi3, 6
  br i1 %t10, label %while.body3, label %while.exit-merge3
while.body3:
  ; while body
  %t11 = sub i32 %k.phi3, 1
  %t12 = call ptr @elem(ptr %t0, i32 %t11)
  %t13 = load i32, ptr %t12
  ; let prev
  %t14 = call ptr @elem(ptr %t0, i32 %k.phi3)
  %t15 = load i32, ptr %t14
  ; let cur
  %t16 = call ptr @elem(ptr %t0, i32 %k.phi3)
  %t17 = add i32 %t13, %t15
  store i32 %t17, ptr %t16
  ; set k
  %k.next3 = add i32 %k.phi3, 1
  br label %while.latch3
while.latch3:
  br label %while.cond3
while.exit-merge3:
  ; sync loop-carried locals to stack
  store i32 %k.phi3, ptr %k.addr
  br label %while.end3
while.end3:
  ; let j
  store i32 11, ptr %j.addr
  ; while condition
  br label %while.pre4
while.pre4:
  %total.init4 = load i32, ptr %total.addr
  %j.init4 = load i32, ptr %j.addr
  br label %while.cond4
while.cond4:
  %total.phi4 = phi i32 [%total.init4, %while.pre4], [%total.next4, %while.latch4]
  %j.phi4 = phi i32 [%j.init4, %while.pre4], [%j.next4, %while.latch4]
  %t18 = icmp sge i32 %j.phi4, 0
  br i1 %t18, label %while.body4, label %while.exit-merge4
while.body4:
  ; while body
  %t19 = call ptr @elem(ptr %src, i32 %j.phi4)
  %t20 = load i32, ptr %t19
  ; let v2
  %t21 = call ptr @elem(ptr %t0, i32 %t20)
  %t22 = load i32, ptr %t21
  %t23 = sub i32 %t22, 1
  ; let pos
  %t24 = call ptr @elem(ptr %dst, i32 %t23)
  store i32 %t20, ptr %t24
  %t25 = call ptr @elem(ptr %t0, i32 %t20)
  store i32 %t23, ptr %t25
  ; set total
  %total.next4 = add i32 %total.phi4, %t20
  ; set j
  %j.next4 = sub i32 %j.phi4, 1
  br label %while.latch4
while.latch4:
  br label %while.cond4
while.exit-merge4:
  ; sync loop-carried locals to stack
  store i32 %total.phi4, ptr %total.addr
  store i32 %j.phi4, ptr %j.addr
  br label %while.end4
while.end4:
  call void @free(ptr %t0)
  ; return
  %t26 = load i32, ptr %total.addr
  ret i32 %t26
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 48)
  ; let src
  %t1 = call ptr @malloc(i64 48)
  ; let dst
  ; if condition
  %t2 = icmp eq ptr %t0, null
  %t3 = icmp eq ptr %t1, null
  %t4 = or i1 %t2, %t3
  br i1 %t4, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t5 = call ptr @elem(ptr %t0, i32 0)
  store i32 3, ptr %t5
  %t6 = call ptr @elem(ptr %t0, i32 1)
  store i32 1, ptr %t6
  %t7 = call ptr @elem(ptr %t0, i32 2)
  store i32 4, ptr %t7
  %t8 = call ptr @elem(ptr %t0, i32 3)
  store i32 1, ptr %t8
  %t9 = call ptr @elem(ptr %t0, i32 4)
  store i32 5, ptr %t9
  %t10 = call ptr @elem(ptr %t0, i32 5)
  store i32 0, ptr %t10
  %t11 = call ptr @elem(ptr %t0, i32 6)
  store i32 2, ptr %t11
  %t12 = call ptr @elem(ptr %t0, i32 7)
  store i32 4, ptr %t12
  %t13 = call ptr @elem(ptr %t0, i32 8)
  store i32 5, ptr %t13
  %t14 = call ptr @elem(ptr %t0, i32 9)
  store i32 3, ptr %t14
  %t15 = call ptr @elem(ptr %t0, i32 10)
  store i32 5, ptr %t15
  %t16 = call ptr @elem(ptr %t0, i32 11)
  store i32 1, ptr %t16
  %t17 = call i32 @counting_sort12(ptr %t0, ptr %t1)
  ; let sum
  call void @free(ptr %t0)
  call void @free(ptr %t1)
  ; return
  ret i32 %t17
}

