; generated by weavec2
; source: test/performance/wir/0152_merge_sorted_halves8_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: elem
; params: ptr, i32
; returns: ptr
define ptr @elem(ptr %a, i32 %idx) {
entry:
  ; return
  %t0 = sext i32 %idx to i64
  %t1 = getelementptr i32, ptr %a, i64 %t0
  ret ptr %t1
}

; function: merge8
; params: ptr, ptr, ptr
; returns: i32
define i32 @merge8(ptr %left, ptr %right, ptr %out) {
entry:
  %i.addr = alloca i32
  %j.addr = alloca i32
  %k.addr = alloca i32
  %checksum.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; let j
  store i32 0, ptr %j.addr
  ; let k
  store i32 0, ptr %k.addr
  ; let checksum
  store i32 0, ptr %checksum.addr
  ; while condition
  br label %while.pre
while.pre:
  %checksum.init0 = load i32, ptr %checksum.addr
  %i.init0 = load i32, ptr %i.addr
  %j.init0 = load i32, ptr %j.addr
  %k.init0 = load i32, ptr %k.addr
  br label %while.cond
while.cond:
  %checksum.phi0 = phi i32 [%checksum.init0, %while.pre], [%checksum.merge1, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.merge1, %while.latch]
  %j.phi0 = phi i32 [%j.init0, %while.pre], [%j.merge1, %while.latch]
  %k.phi0 = phi i32 [%k.init0, %while.pre], [%k.next0, %while.latch]
  %t0 = icmp slt i32 %k.phi0, 8
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t1 = icmp slt i32 %i.phi0, 4
  %t2 = icmp sge i32 %j.phi0, 4
  %t3 = call ptr @elem(ptr %left, i32 %i.phi0)
  %t4 = load i32, ptr %t3
  %t5 = call ptr @elem(ptr %right, i32 %j.phi0)
  %t6 = load i32, ptr %t5
  %t7 = icmp sle i32 %t4, %t6
  %t8 = or i1 %t2, %t7
  %t9 = and i1 %t1, %t8
  br i1 %t9, label %then1, label %else1
then1:
  ; then
  %t10 = call ptr @elem(ptr %left, i32 %i.phi0)
  %t11 = load i32, ptr %t10
  ; let v
  %t12 = call ptr @elem(ptr %out, i32 %k.phi0)
  store i32 %t11, ptr %t12
  ; set checksum
  %checksum.next10 = add i32 %checksum.phi0, %t11
  ; set i
  %i.next10 = add i32 %i.phi0, 1
  br label %endif1
else1:
  ; else
  %t13 = call ptr @elem(ptr %right, i32 %j.phi0)
  %t14 = load i32, ptr %t13
  ; let w
  %t15 = call ptr @elem(ptr %out, i32 %k.phi0)
  store i32 %t14, ptr %t15
  ; set checksum
  %checksum.next11 = add i32 %checksum.phi0, %t14
  ; set j
  %j.next11 = add i32 %j.phi0, 1
  br label %endif1
endif1:
  %i.merge1 = phi i32 [%i.next10, %then1], [%i.phi0, %else1]
  %j.merge1 = phi i32 [%j.phi0, %then1], [%j.next11, %else1]
  %checksum.merge1 = phi i32 [%checksum.next10, %then1], [%checksum.next11, %else1]
  ; set k
  %k.next0 = add i32 %k.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %checksum.phi0, ptr %checksum.addr
  store i32 %i.phi0, ptr %i.addr
  store i32 %j.phi0, ptr %j.addr
  store i32 %k.phi0, ptr %k.addr
  br label %while.end
while.end:
  ; return
  %t16 = load i32, ptr %checksum.addr
  ret i32 %t16
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 16)
  ; let left
  %t1 = call ptr @malloc(i64 16)
  ; let right
  %t2 = call ptr @malloc(i64 32)
  ; let out
  ; if condition
  %t3 = icmp eq ptr %t0, null
  %t4 = icmp eq ptr %t1, null
  %t5 = icmp eq ptr %t2, null
  %t6 = or i1 %t4, %t5
  %t7 = or i1 %t3, %t6
  br i1 %t7, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t8 = call ptr @elem(ptr %t0, i32 0)
  store i32 1, ptr %t8
  %t9 = call ptr @elem(ptr %t0, i32 1)
  store i32 5, ptr %t9
  %t10 = call ptr @elem(ptr %t0, i32 2)
  store i32 9, ptr %t10
  %t11 = call ptr @elem(ptr %t0, i32 3)
  store i32 13, ptr %t11
  %t12 = call ptr @elem(ptr %t1, i32 0)
  store i32 2, ptr %t12
  %t13 = call ptr @elem(ptr %t1, i32 1)
  store i32 6, ptr %t13
  %t14 = call ptr @elem(ptr %t1, i32 2)
  store i32 10, ptr %t14
  %t15 = call ptr @elem(ptr %t1, i32 3)
  store i32 14, ptr %t15
  %t16 = call i32 @merge8(ptr %t0, ptr %t1, ptr %t2)
  ; let sum
  call void @free(ptr %t0)
  call void @free(ptr %t1)
  call void @free(ptr %t2)
  ; return
  ret i32 %t16
}

