; generated by weavec2
; source: test/performance/wir/0154_factorial20_i64.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %n.addr = alloca i32
  %fact.addr = alloca i64
  ; let n
  store i32 1, ptr %n.addr
  ; let fact
  store i64 1, ptr %fact.addr
  ; while condition
  br label %while.pre
while.pre:
  %n.init0 = load i32, ptr %n.addr
  br label %while.cond
while.cond:
  %n.phi0 = phi i32 [%n.init0, %while.pre], [%n.next0, %while.latch]
  %t0 = icmp sle i32 %n.phi0, 20
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set fact
  %t1 = load i64, ptr %fact.addr
  %t2 = sext i32 %n.phi0 to i64
  %t3 = mul i64 %t1, %t2
  store i64 %t3, ptr %fact.addr
  ; set n
  %n.next0 = add i32 %n.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %n.phi0, ptr %n.addr
  br label %while.end
while.end:
  ; return
  %t4 = load i64, ptr %fact.addr
  %t5 = srem i64 %t4, 1000000007
  %t6 = trunc i64 %t5 to i32
  ret i32 %t6
}

