; generated by weavec2
; source: test/performance/wir/0156_gcd_i64.wir
; core-version: 1

; function: gcd_i64
; params: i64, i64
; returns: i64
define i64 @gcd_i64(i64 %a, i64 %b) {
entry:
  %x.addr = alloca i64
  %y.addr = alloca i64
  ; let x
  store i64 %a, ptr %x.addr
  ; let y
  store i64 %b, ptr %y.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i64, ptr %y.addr
  %t1 = icmp ne i64 %t0, 0
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  %t2 = load i64, ptr %x.addr
  %t3 = load i64, ptr %y.addr
  %t4 = srem i64 %t2, %t3
  ; let r
  ; set x
  %t5 = load i64, ptr %y.addr
  store i64 %t5, ptr %x.addr
  ; set y
  store i64 %t4, ptr %y.addr
  br label %while.cond
while.end:
  ; return
  %t6 = load i64, ptr %x.addr
  ret i64 %t6
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i64 @gcd_i64(i64 462, i64 1071)
  %t1 = trunc i64 %t0 to i32
  ret i32 %t1
}

