; generated by weavec2
; source: test/performance/wir/0156_gcd_i64.wir
; core-version: 1

; function: gcd_i64
; params: i64, i64
; returns: i64
define i64 @gcd_i64(i64 %a, i64 %b) {
entry:
  %x.addr = alloca i64
  %y.addr = alloca i64
  ; let x
  store i64 %a, ptr %x.addr
  ; let y
  store i64 %b, ptr %y.addr
  ; while condition
  br label %while.pre
while.pre:
  %x.init0 = load i64, ptr %x.addr
  %y.init0 = load i64, ptr %y.addr
  br label %while.cond
while.cond:
  %x.phi0 = phi i64 [%x.init0, %while.pre], [%y.phi0, %while.latch]
  %y.phi0 = phi i64 [%y.init0, %while.pre], [%y.next0, %while.latch]
  %t0 = icmp ne i64 %y.phi0, 0
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  %t1 = srem i64 %x.phi0, %y.phi0
  ; let r
  ; set x
  ; set y
  %y.next0 = srem i64 %x.phi0, %y.phi0
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i64 %x.phi0, ptr %x.addr
  store i64 %y.phi0, ptr %y.addr
  br label %while.end
while.end:
  ; return
  %t2 = load i64, ptr %x.addr
  ret i64 %t2
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i64 @gcd_i64(i64 462, i64 1071)
  %t1 = trunc i64 %t0 to i32
  ret i32 %t1
}

