; generated by weavec2
; source: test/performance/wir/0158_fibonacci30_i64.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %i.addr = alloca i32
  %prev.addr = alloca i64
  %cur.addr = alloca i64
  ; let i
  store i32 2, ptr %i.addr
  ; let prev
  store i64 0, ptr %prev.addr
  ; let cur
  store i64 1, ptr %cur.addr
  ; while condition
  br label %while.pre
while.pre:
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp sle i32 %i.phi0, 30
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  %t1 = load i64, ptr %prev.addr
  %t2 = load i64, ptr %cur.addr
  %t3 = add i64 %t1, %t2
  ; let next
  ; set prev
  %t4 = load i64, ptr %cur.addr
  store i64 %t4, ptr %prev.addr
  ; set cur
  store i64 %t3, ptr %cur.addr
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t5 = load i64, ptr %cur.addr
  %t6 = srem i64 %t5, 1000000007
  %t7 = trunc i64 %t6 to i32
  ret i32 %t7
}

