; generated by weavec2
; source: test/performance/wir/0159_power_mod_i64.wir
; core-version: 1

; function: pow_mod
; params: i64, i32, i64
; returns: i64
define i64 @pow_mod(i64 %base, i32 %exp, i64 %modulus) {
entry:
  %result.addr = alloca i64
  %b.addr = alloca i64
  %e.addr = alloca i32
  ; let result
  store i64 1, ptr %result.addr
  %t0 = srem i64 %base, %modulus
  ; let b
  store i64 %t0, ptr %b.addr
  ; let e
  store i32 %exp, ptr %e.addr
  ; while condition
  br label %while.pre
while.pre:
  %e.init0 = load i32, ptr %e.addr
  br label %while.cond
while.cond:
  %e.phi0 = phi i32 [%e.init0, %while.pre], [%e.next0, %while.latch]
  %t1 = icmp sgt i32 %e.phi0, 0
  br i1 %t1, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t2 = srem i32 %e.phi0, 2
  %t3 = icmp eq i32 %t2, 1
  br i1 %t3, label %then1, label %endif1
then1:
  ; then
  ; set result
  %t4 = load i64, ptr %result.addr
  %t5 = load i64, ptr %b.addr
  %t6 = mul i64 %t4, %t5
  %t7 = srem i64 %t6, %modulus
  store i64 %t7, ptr %result.addr
  br label %endif1
endif1:
  ; set b
  %t8 = load i64, ptr %b.addr
  %t9 = load i64, ptr %b.addr
  %t10 = mul i64 %t8, %t9
  %t11 = srem i64 %t10, %modulus
  store i64 %t11, ptr %b.addr
  ; set e
  %e.next0 = sdiv i32 %e.phi0, 2
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %e.phi0, ptr %e.addr
  br label %while.end
while.end:
  ; return
  %t12 = load i64, ptr %result.addr
  ret i64 %t12
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i64 @pow_mod(i64 3, i32 13, i64 1000000007)
  %t1 = trunc i64 %t0 to i32
  ret i32 %t1
}

