; generated by weavec2
; source: test/performance/wir/0162_bitwise_mix_i64.wir
; core-version: 1

; function: mix64
; params: i64
; returns: i64
define i64 @mix64(i64 %seed) {
entry:
  %x.addr = alloca i64
  %i.addr = alloca i32
  ; let x
  store i64 %seed, ptr %x.addr
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre
while.pre:
  %x.init0 = load i64, ptr %x.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %x.phi0 = phi i64 [%x.init0, %while.pre], [%x.next0, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp slt i32 %i.phi0, 64
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set x
  %t1 = and i64 %x.phi0, 255
  %t2 = shl i64 %t1, 3
  %t3 = ashr i64 %x.phi0, 5
  %t4 = xor i64 %t2, %t3
  %x.next0 = add i64 %t4, 0
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i64 %x.phi0, ptr %x.addr
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t5 = load i64, ptr %x.addr
  ret i64 %t5
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i64 @mix64(i64 0)
  %t1 = srem i64 %t0, 1000000007
  %t2 = trunc i64 %t1 to i32
  ret i32 %t2
}

