; generated by weavec2
; source: test/performance/wir/0163_horner_poly_i64.wir
; core-version: 1

; function: horner6
; params: i64
; returns: i64
define i64 @horner6(i64 %x) {
entry:
  %acc.addr = alloca i64
  %i.addr = alloca i32
  ; let acc
  store i64 7, ptr %acc.addr
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre
while.pre:
  %acc.init0 = load i64, ptr %acc.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %acc.phi0 = phi i64 [%acc.init0, %while.pre], [%acc.next0, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp slt i32 %i.phi0, 6
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set acc
  %t1 = mul i64 %acc.phi0, %x
  %t2 = sext i32 %i.phi0 to i64
  %t3 = add i64 1, %t2
  %acc.next0 = add i64 %t1, %t3
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i64 %acc.phi0, ptr %acc.addr
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t4 = load i64, ptr %acc.addr
  ret i64 %t4
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i64 @horner6(i64 11)
  %t1 = srem i64 %t0, 1000000007
  %t2 = trunc i64 %t1 to i32
  ret i32 %t2
}

