; generated by weavec2
; source: test/performance/wir/0165_const_f32_add.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = sitofp i32 2 to float
  %t1 = sitofp i32 3 to float
  %t2 = fadd float %t0, %t1
  %t3 = fptosi float %t2 to i32
  ret i32 %t3
}

