; generated by weavec2
; source: test/performance/wir/0167_dot_product4_f32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = sitofp i32 1 to float
  ; let a0
  %t1 = sitofp i32 2 to float
  ; let a1
  %t2 = sitofp i32 3 to float
  ; let a2
  %t3 = sitofp i32 4 to float
  ; let a3
  %t4 = sitofp i32 1 to float
  ; let b0
  %t5 = sitofp i32 2 to float
  ; let b1
  %t6 = sitofp i32 3 to float
  ; let b2
  %t7 = sitofp i32 4 to float
  ; let b3
  %t8 = fmul float %t0, %t4
  %t9 = fmul float %t1, %t5
  %t10 = fadd float %t8, %t9
  %t11 = fmul float %t2, %t6
  %t12 = fmul float %t3, %t7
  %t13 = fadd float %t11, %t12
  %t14 = fadd float %t10, %t13
  ; let sum
  ; return
  %t15 = fptosi float %t14 to i32
  ret i32 %t15
}

