; generated by weavec2
; source: test/performance/wir/0168_newton_sqrt_f32.wir
; core-version: 1

; function: sqrt_newton
; params: float
; returns: float
define float @sqrt_newton(float %x) {
entry:
  %guess.addr = alloca float
  %i.addr = alloca i32
  %t0 = sitofp i32 1 to float
  %t1 = fadd float %x, %t0
  %t2 = sitofp i32 2 to float
  %t3 = fdiv float %t1, %t2
  ; let guess
  store float %t3, ptr %guess.addr
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre
while.pre:
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t4 = icmp slt i32 %i.phi0, 8
  br i1 %t4, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set guess
  %t5 = load float, ptr %guess.addr
  %t6 = load float, ptr %guess.addr
  %t7 = fdiv float %x, %t6
  %t8 = fadd float %t5, %t7
  %t9 = sitofp i32 2 to float
  %t10 = fdiv float %t8, %t9
  store float %t10, ptr %guess.addr
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t11 = load float, ptr %guess.addr
  ret float %t11
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = sitofp i32 2 to float
  %t1 = call float @sqrt_newton(float %t0)
  %t2 = sitofp i32 1000 to float
  %t3 = fmul float %t1, %t2
  %t4 = fptosi float %t3 to i32
  ret i32 %t4
}

