; generated by weavec2
; source: test/performance/wir/0169_const_f64_add.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = sitofp i32 2 to double
  %t1 = sitofp i32 3 to double
  %t2 = fadd double %t0, %t1
  %t3 = fptosi double %t2 to i32
  ret i32 %t3
}

