; generated by weavec2
; source: test/performance/wir/0170_sum_range_f64.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %i.addr = alloca i32
  %sum.addr = alloca double
  ; let i
  store i32 1, ptr %i.addr
  %t0 = sitofp i32 0 to double
  ; let sum
  store double %t0, ptr %sum.addr
  ; while condition
  br label %while.pre
while.pre:
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t1 = icmp sle i32 %i.phi0, 120
  br i1 %t1, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set sum
  %t2 = load double, ptr %sum.addr
  %t3 = sitofp i32 %i.phi0 to double
  %t4 = fadd double %t2, %t3
  store double %t4, ptr %sum.addr
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t5 = load double, ptr %sum.addr
  %t6 = fptosi double %t5 to i32
  ret i32 %t6
}

