; generated by weavec2
; source: test/performance/wir/0171_factorial12_i64.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %i.addr = alloca i32
  %acc.addr = alloca i64
  ; let i
  store i32 2, ptr %i.addr
  ; let acc
  store i64 1, ptr %acc.addr
  ; while condition
  br label %while.pre
while.pre:
  %acc.init0 = load i64, ptr %acc.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %acc.phi0 = phi i64 [%acc.init0, %while.pre], [%acc.next0, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp sle i32 %i.phi0, 12
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set acc
  %t1 = sext i32 %i.phi0 to i64
  %acc.next0 = mul i64 %acc.phi0, %t1
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i64 %acc.phi0, ptr %acc.addr
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t2 = load i64, ptr %acc.addr
  %t3 = srem i64 %t2, 1000000007
  %t4 = trunc i64 %t3 to i32
  ret i32 %t4
}

