; generated by weavec2
; source: test/performance/wir/0172_horner_poly_f32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %i.addr = alloca i32
  %acc.addr = alloca float
  ; let i
  store i32 0, ptr %i.addr
  %t0 = sitofp i32 0 to float
  ; let acc
  store float %t0, ptr %acc.addr
  ; while condition
  br label %while.pre
while.pre:
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t1 = icmp slt i32 %i.phi0, 8
  br i1 %t1, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set acc
  %t2 = load float, ptr %acc.addr
  %t3 = sitofp i32 3 to float
  %t4 = fmul float %t2, %t3
  %t5 = sitofp i32 %i.phi0 to float
  %t6 = fadd float %t4, %t5
  store float %t6, ptr %acc.addr
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t7 = load float, ptr %acc.addr
  %t8 = fptosi float %t7 to i32
  ret i32 %t8
}

