; generated by weavec2
; source: test/performance/wir/0173_sum_range_i64_acc.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %i.addr = alloca i32
  %total.addr = alloca i64
  ; let i
  store i32 1, ptr %i.addr
  ; let total
  store i64 0, ptr %total.addr
  ; while condition
  br label %while.pre
while.pre:
  %total.init0 = load i64, ptr %total.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %total.phi0 = phi i64 [%total.init0, %while.pre], [%total.next0, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp sle i32 %i.phi0, 200
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set total
  %t1 = sext i32 %i.phi0 to i64
  %total.next0 = add i64 %total.phi0, %t1
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i64 %total.phi0, ptr %total.addr
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t2 = load i64, ptr %total.addr
  %t3 = trunc i64 %t2 to i32
  ret i32 %t3
}

