; generated by weavec2
; source: test/performance/wir/0175_sum_squares_i64.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %i.addr = alloca i32
  %sum.addr = alloca i64
  ; let i
  store i32 1, ptr %i.addr
  ; let sum
  store i64 0, ptr %sum.addr
  ; while condition
  br label %while.pre
while.pre:
  %sum.init0 = load i64, ptr %sum.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %sum.phi0 = phi i64 [%sum.init0, %while.pre], [%sum.next0, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp sle i32 %i.phi0, 100
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; let sq (deferred)
  ; set sum
  %t1 = sext i32 %i.phi0 to i64
  %t2 = sext i32 %i.phi0 to i64
  %t3 = mul i64 %t1, %t2
  %sum.next0 = add i64 %sum.phi0, %t3
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i64 %sum.phi0, ptr %sum.addr
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t4 = load i64, ptr %sum.addr
  %t5 = trunc i64 %t4 to i32
  ret i32 %t5
}

