; generated by weavec2
; source: test/performance/wir/02_return_42.wir
; core-version: 1

; string literals


; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  ret i32 42
}

