; generated by weavec2
; source: test/performance/wir/03_add.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = add i32 20, 22
  ret i32 %t0
}

