; generated by weavec2
; source: test/performance/wir/07_if.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = icmp slt i32 1, 2
  br i1 %t0, label %then0, label %else0
then0:
  ; then
  ; return
  ret i32 42
else0:
  ; else
  ; return
  ret i32 0
}

