; generated by weavec2
; source: test/performance/wir/08_while.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %i.addr = alloca i32
  %sum.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; let sum
  store i32 0, ptr %sum.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp slt i32 %t0, 7
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; set sum
  %t2 = load i32, ptr %sum.addr
  %t3 = add i32 %t2, 6
  store i32 %t3, ptr %sum.addr
  ; set i
  %t4 = load i32, ptr %i.addr
  %t5 = add i32 %t4, 1
  store i32 %t5, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t6 = load i32, ptr %sum.addr
  ret i32 %t6
}

