; generated by weavec2
; source: test/performance/wir/11_const_i64.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; let x
  ; return
  %t0 = trunc i64 42 to i32
  ret i32 %t0
}

