; generated by weavec2
; source: test/performance/wir/14_bool_ops.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = or i1 false, true
  %t1 = and i1 true, %t0
  br i1 %t1, label %then, label %else
then:
  ; then
  ; return
  ret i32 42
else:
  ; else
  ; return
  ret i32 0
}

