; generated by weavec2
; source: test/performance/wir/17_ptr_add_store_load_i64.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 16)
  ; let p
  %p.addr = alloca ptr
  store ptr %t0, ptr %p.addr
  ; if condition
  %t1 = load ptr, ptr %p.addr
  %t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then, label %else
then:
  ; then
  ; return
  ret i32 0
else:
  ; else
  br label %endif
endif:
  %t3 = load ptr, ptr %p.addr
  store i64 20, ptr %t3
  %t4 = load ptr, ptr %p.addr
  %t5 = getelementptr i8, ptr %t4, i64 8
  store i64 22, ptr %t5
  %t6 = load ptr, ptr %p.addr
  %t7 = load i64, ptr %t6
  ; let a
  %a.addr = alloca i64
  store i64 %t7, ptr %a.addr
  %t8 = load ptr, ptr %p.addr
  %t9 = getelementptr i8, ptr %t8, i64 8
  %t10 = load i64, ptr %t9
  ; let b
  %b.addr = alloca i64
  store i64 %t10, ptr %b.addr
  %t11 = load ptr, ptr %p.addr
  call void @free(ptr %t11)
  ; return
  %t12 = load i64, ptr %a.addr
  %t13 = load i64, ptr %b.addr
  %t14 = add i64 %t12, %t13
  %t15 = trunc i64 %t14 to i32
  ret i32 %t15
}

