; generated by weavec2
; source: test/performance/wir/21_call_ptr.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: make_ptr
; params: none
; returns: ptr
define ptr @make_ptr() {
entry:
  ; return
  %t0 = call ptr @malloc(i64 8)
  ret ptr %t0
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @make_ptr()
  ; let p
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %else
then:
  ; then
  ; return
  ret i32 0
else:
  ; else
  call void @free(ptr %t0)
  ; return
  ret i32 42
}

