; generated by weavec2
; source: test/performance/wir/22_return_void.wir
; core-version: 1

; function: noop
; params: none
; returns: void
define void @noop() {
entry:
  ret void
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  call void @noop()
  ; return
  ret i32 42
}

