; generated by weavec2
; source: test/performance/wir/23_mod_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = srem i32 42, 10
  ret i32 %t0
}

