; generated by weavec2
; source: test/performance/wir/29_const_string_ptr.wir
; core-version: 1

; declarations

declare i32 @puts(ptr)

; string literals

@.str0 = private unnamed_addr constant [28 x i8] c"hello from const_string_ptr\00"

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = getelementptr [28 x i8], ptr @.str0, i64 0, i64 0
  %t1 = call i32 @puts(ptr %t0)
  ; return
  ret i32 42
}

