; generated by weavec2
; source: test/performance/wir/35_sub_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = sub i32 50, 8
  ret i32 %t0
}

