; generated by weavec2
; source: test/performance/wir/36_mul_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = mul i32 6, 7
  ret i32 %t0
}

