; generated by weavec2
; source: test/performance/wir/37_div_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = sdiv i32 126, 3
  ret i32 %t0
}

