; generated by weavec2
; source: test/performance/wir/41_load_store_ptr.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 8)
  ; let slot
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @malloc(i64 8)
  ; let data
  ; if condition
  %t3 = icmp eq ptr %t2, null
  br i1 %t3, label %then1, label %endif1
then1:
  ; then
  call void @free(ptr %t0)
  ; return
  ret i32 0
endif1:
  store ptr %t2, ptr %t0
  %t4 = load ptr, ptr %t0
  ; let loaded
  store i64 42, ptr %t4
  %t5 = load i64, ptr %t2
  ; let value
  call void @free(ptr %t2)
  call void @free(ptr %t0)
  ; return
  %t6 = trunc i64 %t5 to i32
  ret i32 %t6
}

