; generated by weavec2
; source: test/performance/wir/42_empty_do.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = icmp eq i32 1, 2
  br i1 %t0, label %then, label %endif
then:
  ; then
  br label %endif
endif:
  ; return
  ret i32 42
}

