; generated by weavec2
; source: test/performance/wir/43_if_fallthrough_join.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; let x
  %x.addr = alloca i32
  store i32 0, ptr %x.addr
  ; if condition
  %t0 = icmp slt i32 1, 2
  br i1 %t0, label %then, label %else
then:
  ; then
  ; set x
  store i32 42, ptr %x.addr
  br label %endif
else:
  ; else
  ; set x
  store i32 0, ptr %x.addr
  br label %endif
endif:
  ; return
  %t1 = load i32, ptr %x.addr
  ret i32 %t1
}

