; generated by weavec2
; source: test/performance/wir/44_while_zero_iterations.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %i.addr = alloca i32
  %sum.addr = alloca i32
  ; let i
  store i32 10, ptr %i.addr
  ; let sum
  store i32 42, ptr %sum.addr
  ; while condition
  br label %while.pre
while.pre:
  %sum.init0 = load i32, ptr %sum.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %sum.phi0 = phi i32 [%sum.init0, %while.pre], [0, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp slt i32 %i.phi0, 5
  br i1 %t0, label %while.body, label %while.end
while.body:
  ; while body
  ; set sum
  %sum.next0 = add i32 0, 0
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.end:
  ; return
  ret i32 %sum.phi0
}

