; generated by weavec2
; source: test/performance/wir/44_while_zero_iterations.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; let i
  %i.addr = alloca i32
  store i32 10, ptr %i.addr
  ; let sum
  %sum.addr = alloca i32
  store i32 42, ptr %sum.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp slt i32 %t0, 5
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; set sum
  store i32 0, ptr %sum.addr
  ; set i
  %t2 = load i32, ptr %i.addr
  %t3 = add i32 %t2, 1
  store i32 %t3, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t4 = load i32, ptr %sum.addr
  ret i32 %t4
}

