; generated by weavec2
; source: test/performance/wir/45_nested_while.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; let outer
  %outer.addr = alloca i32
  store i32 0, ptr %outer.addr
  ; let total
  %total.addr = alloca i32
  store i32 0, ptr %total.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %outer.addr
  %t1 = icmp slt i32 %t0, 2
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let inner
  %inner.addr = alloca i32
  store i32 0, ptr %inner.addr
  ; while condition
  br label %while.cond1
while.cond1:
  %t2 = load i32, ptr %inner.addr
  %t3 = icmp slt i32 %t2, 3
  br i1 %t3, label %while.body1, label %while.end1
while.body1:
  ; while body
  ; set total
  %t4 = load i32, ptr %total.addr
  %t5 = add i32 %t4, 7
  store i32 %t5, ptr %total.addr
  ; set inner
  %t6 = load i32, ptr %inner.addr
  %t7 = add i32 %t6, 1
  store i32 %t7, ptr %inner.addr
  br label %while.cond1
while.end1:
  ; set outer
  %t8 = load i32, ptr %outer.addr
  %t9 = add i32 %t8, 1
  store i32 %t9, ptr %outer.addr
  br label %while.cond
while.end:
  ; return
  %t10 = load i32, ptr %total.addr
  ret i32 %t10
}

