; generated by weavec2
; source: test/performance/wir/45_nested_while.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %outer.addr = alloca i32
  %total.addr = alloca i32
  %inner.addr = alloca i32
  ; let outer
  store i32 0, ptr %outer.addr
  ; let total
  store i32 0, ptr %total.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %outer.addr
  %t1 = icmp slt i32 %t0, 2
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let inner
  store i32 0, ptr %inner.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %total.init1 = load i32, ptr %total.addr
  %inner.init1 = load i32, ptr %inner.addr
  br label %while.cond1
while.cond1:
  %total.phi1 = phi i32 [%total.init1, %while.pre1], [%total.next1, %while.latch1]
  %inner.phi1 = phi i32 [%inner.init1, %while.pre1], [%inner.next1, %while.latch1]
  %t2 = icmp slt i32 %inner.phi1, 3
  br i1 %t2, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  ; set total
  %total.next1 = add i32 %total.phi1, 7
  ; set inner
  %inner.next1 = add i32 %inner.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %total.phi1, ptr %total.addr
  store i32 %inner.phi1, ptr %inner.addr
  br label %while.end1
while.end1:
  ; set outer
  %t3 = load i32, ptr %outer.addr
  %t4 = add i32 %t3, 1
  store i32 %t4, ptr %outer.addr
  br label %while.cond
while.end:
  ; return
  %t5 = load i32, ptr %total.addr
  ret i32 %t5
}

