; generated by weavec2
; source: test/performance/wir/47_multiple_externs_used_subset.wir
; core-version: 1

; declarations

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 8)
  ; let p
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  call void @free(ptr %t0)
  ; return
  ret i32 42
}

