; generated by weavec2
; source: test/performance/wir/49_negative_i32_literal.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = add i32 -8, 50
  ret i32 %t0
}

