; generated by weavec2
; source: test/performance/wir/57_integration_memory_flow.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: write_values
; params: ptr, i32
; returns: void
define void @write_values(ptr %buffer, i32 %count) {
entry:
  %i.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre
while.pre:
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.body]
  %t0 = icmp slt i32 %i.phi0, %count
  br i1 %t0, label %while.body, label %while.end
while.body:
  ; while body
  %t1 = sext i32 %i.phi0 to i64
  %t2 = mul i64 %t1, 4
  %t3 = getelementptr i8, ptr %buffer, i64 %t2
  %t4 = mul i32 %i.phi0, 10
  store i32 %t4, ptr %t3
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.cond
while.end:
  ret void
}

; function: sum_values
; params: ptr, i32
; returns: i32
define i32 @sum_values(ptr %buffer, i32 %count) {
entry:
  %sum.addr = alloca i32
  %i.addr = alloca i32
  ; let sum
  store i32 0, ptr %sum.addr
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre
while.pre:
  %sum.init0 = load i32, ptr %sum.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %sum.phi0 = phi i32 [%sum.init0, %while.pre], [%sum.next0, %while.body]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.body]
  %t0 = icmp slt i32 %i.phi0, %count
  br i1 %t0, label %while.body, label %while.end
while.body:
  ; while body
  ; set sum
  %t1 = sext i32 %i.phi0 to i64
  %t2 = mul i64 %t1, 4
  %t3 = getelementptr i8, ptr %buffer, i64 %t2
  %t4 = load i32, ptr %t3
  %sum.next0 = add i32 %sum.phi0, %t4
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.cond
while.end:
  ; return
  ret i32 %sum.phi0
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 20)
  ; let buffer
  call void @write_values(ptr %t0, i32 5)
  %t1 = call i32 @sum_values(ptr %t0, i32 5)
  ; let result
  call void @free(ptr %t0)
  ; return
  ret i32 %t1
}

