; generated by weavec2
; source: test/performance/wir/60_discard_call_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)

; function: touch
; params: ptr
; returns: i32
define i32 @touch(ptr %p) {
entry:
  store i32 42, ptr %p
  ; return
  ret i32 0
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 4)
  ; let p
  %t1 = call i32 @touch(ptr %t0)
  ; return
  %t2 = load i32, ptr %t0
  ret i32 %t2
}

