; generated by weavec2
; source: test/performance/wir/61_fibonacci_iterative.wir
; core-version: 1

; function: fib
; params: i32
; returns: i32
define i32 @fib(i32 %n) {
entry:
  %prev.addr = alloca i32
  %curr.addr = alloca i32
  %i.addr = alloca i32
  ; if condition
  %t0 = icmp sle i32 %n, 1
  br i1 %t0, label %then, label %endif
then:
  ; then
  ; return
  ret i32 %n
endif:
  ; let prev
  store i32 0, ptr %prev.addr
  ; let curr
  store i32 1, ptr %curr.addr
  ; let i
  store i32 2, ptr %i.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %prev.init1 = load i32, ptr %prev.addr
  %curr.init1 = load i32, ptr %curr.addr
  %i.init1 = load i32, ptr %i.addr
  br label %while.cond1
while.cond1:
  %prev.phi1 = phi i32 [%prev.init1, %while.pre1], [%curr.phi1, %while.latch1]
  %curr.phi1 = phi i32 [%curr.init1, %while.pre1], [%curr.next1, %while.latch1]
  %i.phi1 = phi i32 [%i.init1, %while.pre1], [%i.next1, %while.latch1]
  %t1 = icmp sle i32 %i.phi1, %n
  br i1 %t1, label %while.body1, label %while.end1
while.body1:
  ; while body
  %t2 = add i32 %prev.phi1, %curr.phi1
  ; let next
  ; set prev
  %prev.next1 = add i32 %curr.phi1, 0
  ; set curr
  %curr.next1 = add i32 %t2, 0
  ; set i
  %i.next1 = add i32 %i.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.end1:
  store i32 %prev.phi1, ptr %prev.addr
  store i32 %curr.phi1, ptr %curr.addr
  store i32 %i.phi1, ptr %i.addr
  ; return
  %t3 = load i32, ptr %curr.addr
  ret i32 %t3
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @fib(i32 10)
  ret i32 %t0
}

