; generated by weavec2
; source: test/performance/wir/67_euclid_gcd_i32.wir
; core-version: 1

; function: gcd
; params: i32, i32
; returns: i32
define i32 @gcd(i32 %a, i32 %b) {
entry:
  %x.addr = alloca i32
  %y.addr = alloca i32
  ; let x
  store i32 %a, ptr %x.addr
  ; let y
  store i32 %b, ptr %y.addr
  ; while condition
  br label %while.pre
while.pre:
  %x.init0 = load i32, ptr %x.addr
  %y.init0 = load i32, ptr %y.addr
  br label %while.cond
while.cond:
  %x.phi0 = phi i32 [%x.init0, %while.pre], [%y.phi0, %while.body]
  %y.phi0 = phi i32 [%y.init0, %while.pre], [%y.next0, %while.body]
  %t0 = icmp ne i32 %y.phi0, 0
  br i1 %t0, label %while.body, label %while.end
while.body:
  ; while body
  %t1 = srem i32 %x.phi0, %y.phi0
  ; let r
  ; set x
  ; set y
  %y.next0 = add i32 %t1, 0
  br label %while.cond
while.end:
  ; return
  ret i32 %x.phi0
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @gcd(i32 462, i32 1071)
  %t1 = add i32 %t0, 21
  ret i32 %t1
}

