; generated by weavec2
; source: test/performance/wir/68_binary_search_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %t0 = sext i32 %index to i64
  %t1 = getelementptr i32, ptr %base, i64 %t0
  ret ptr %t1
}

; function: search7
; params: ptr, i32
; returns: i32
define i32 @search7(ptr %items, i32 %target) {
entry:
  %low.addr = alloca i32
  %high.addr = alloca i32
  %result.addr = alloca i32
  %active.addr = alloca i32
  ; let low
  store i32 0, ptr %low.addr
  ; let high
  store i32 6, ptr %high.addr
  ; let result
  store i32 -1, ptr %result.addr
  ; let active
  store i32 1, ptr %active.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %low.addr
  %t1 = load i32, ptr %high.addr
  %t2 = icmp sle i32 %t0, %t1
  %t3 = load i32, ptr %active.addr
  %t4 = icmp ne i32 %t3, 0
  %t5 = and i1 %t2, %t4
  br i1 %t5, label %while.body, label %while.end
while.body:
  ; while body
  %t6 = load i32, ptr %low.addr
  %t7 = load i32, ptr %high.addr
  %t8 = add i32 %t6, %t7
  %t9 = sdiv i32 %t8, 2
  ; let mid
  %t10 = call ptr @elem_ptr(ptr %items, i32 %t9)
  %t11 = load i32, ptr %t10
  ; let value
  ; if condition
  %t12 = icmp eq i32 %t11, %target
  br i1 %t12, label %then1, label %else1
then1:
  ; then
  ; set result
  store i32 %t9, ptr %result.addr
  ; set active
  store i32 0, ptr %active.addr
  br label %endif1
else1:
  ; else
  ; if condition
  %t13 = icmp slt i32 %t11, %target
  br i1 %t13, label %then2, label %else2
then2:
  ; then
  ; set low
  %t14 = add i32 %t9, 1
  store i32 %t14, ptr %low.addr
  br label %endif2
else2:
  ; else
  ; set high
  %t15 = sub i32 %t9, 1
  store i32 %t15, ptr %high.addr
  br label %endif2
endif2:
  br label %endif1
endif1:
  br label %while.cond
while.end:
  ; return
  %t16 = load i32, ptr %result.addr
  ret i32 %t16
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 28)
  ; let items
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @elem_ptr(ptr %t0, i32 0)
  store i32 1, ptr %t2
  %t3 = call ptr @elem_ptr(ptr %t0, i32 1)
  store i32 3, ptr %t3
  %t4 = call ptr @elem_ptr(ptr %t0, i32 2)
  store i32 5, ptr %t4
  %t5 = call ptr @elem_ptr(ptr %t0, i32 3)
  store i32 7, ptr %t5
  %t6 = call ptr @elem_ptr(ptr %t0, i32 4)
  store i32 9, ptr %t6
  %t7 = call ptr @elem_ptr(ptr %t0, i32 5)
  store i32 11, ptr %t7
  %t8 = call ptr @elem_ptr(ptr %t0, i32 6)
  store i32 13, ptr %t8
  %t9 = call i32 @search7(ptr %t0, i32 9)
  ; let index
  call void @free(ptr %t0)
  ; return
  %t10 = add i32 %t9, 38
  ret i32 %t10
}

