; generated by weavec2
; source: test/performance/wir/69_sieve_count_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %t0 = sext i32 %index to i64
  %t1 = getelementptr i32, ptr %base, i64 %t0
  ret ptr %t1
}

; function: count_primes16
; params: ptr
; returns: i32
define i32 @count_primes16(ptr %flags) {
entry:
  %i.addr = alloca i32
  %p.addr = alloca i32
  %multiple.addr = alloca i32
  %count.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre
while.pre:
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp sle i32 %i.phi0, 16
  br i1 %t0, label %while.body, label %while.end
while.body:
  ; while body
  %t1 = call ptr @elem_ptr(ptr %flags, i32 %i.phi0)
  store i32 1, ptr %t1
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.end:
  store i32 %i.phi0, ptr %i.addr
  %t2 = call ptr @elem_ptr(ptr %flags, i32 0)
  store i32 0, ptr %t2
  %t3 = call ptr @elem_ptr(ptr %flags, i32 1)
  store i32 0, ptr %t3
  ; let p
  store i32 2, ptr %p.addr
  ; while condition
  br label %while.cond1
while.cond1:
  %t4 = load i32, ptr %p.addr
  %t5 = load i32, ptr %p.addr
  %t6 = mul i32 %t4, %t5
  %t7 = icmp sle i32 %t6, 16
  br i1 %t7, label %while.body1, label %while.end1
while.body1:
  ; while body
  ; if condition
  %t8 = load i32, ptr %p.addr
  %t9 = call ptr @elem_ptr(ptr %flags, i32 %t8)
  %t10 = load i32, ptr %t9
  %t11 = icmp ne i32 %t10, 0
  br i1 %t11, label %then2, label %endif2
then2:
  ; then
  %t12 = load i32, ptr %p.addr
  %t13 = load i32, ptr %p.addr
  %t14 = mul i32 %t12, %t13
  ; let multiple
  store i32 %t14, ptr %multiple.addr
  ; while condition
  br label %while.pre3
while.pre3:
  %multiple.init3 = load i32, ptr %multiple.addr
  br label %while.cond3
while.cond3:
  %multiple.phi3 = phi i32 [%multiple.init3, %while.pre3], [%multiple.next320, %while.latch3]
  %t15 = icmp sle i32 %multiple.phi3, 16
  br i1 %t15, label %while.body3, label %while.end3
while.body3:
  ; while body
  %t16 = call ptr @elem_ptr(ptr %flags, i32 %multiple.phi3)
  store i32 0, ptr %t16
  ; set multiple
  %t17 = load i32, ptr %p.addr
  %multiple.next320 = add i32 %multiple.phi3, %t17
  br label %while.latch3
while.latch3:
  br label %while.cond3
while.end3:
  store i32 %multiple.phi3, ptr %multiple.addr
  br label %endif2
endif2:
  ; set p
  %t18 = load i32, ptr %p.addr
  %t19 = add i32 %t18, 1
  store i32 %t19, ptr %p.addr
  br label %while.cond1
while.end1:
  ; let count
  store i32 0, ptr %count.addr
  ; set i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre4
while.pre4:
  %count.init4 = load i32, ptr %count.addr
  %i.init4 = load i32, ptr %i.addr
  br label %while.cond4
while.cond4:
  %count.phi4 = phi i32 [%count.init4, %while.pre4], [%count.next4, %while.latch4]
  %i.phi4 = phi i32 [%i.init4, %while.pre4], [%i.next4, %while.latch4]
  %t20 = icmp sle i32 %i.phi4, 16
  br i1 %t20, label %while.body4, label %while.end4
while.body4:
  ; while body
  ; set count
  %t21 = call ptr @elem_ptr(ptr %flags, i32 %i.phi4)
  %t22 = load i32, ptr %t21
  %count.next4 = add i32 %count.phi4, %t22
  ; set i
  %i.next4 = add i32 %i.phi4, 1
  br label %while.latch4
while.latch4:
  br label %while.cond4
while.end4:
  store i32 %count.phi4, ptr %count.addr
  store i32 %i.phi4, ptr %i.addr
  ; return
  %t23 = load i32, ptr %count.addr
  ret i32 %t23
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 68)
  ; let flags
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call i32 @count_primes16(ptr %t0)
  ; let count
  call void @free(ptr %t0)
  ; return
  %t3 = add i32 %t2, 36
  ret i32 %t3
}

