; generated by weavec2
; source: test/performance/wir/71_collatz_i32.wir
; core-version: 1

; function: collatz_steps
; params: i32
; returns: i32
define i32 @collatz_steps(i32 %start) {
entry:
  %n.addr = alloca i32
  %steps.addr = alloca i32
  ; let n
  store i32 %start, ptr %n.addr
  ; let steps
  store i32 0, ptr %steps.addr
  ; while condition
  br label %while.pre
while.pre:
  %n.init0 = load i32, ptr %n.addr
  %n.init0 = load i32, ptr %n.addr
  %steps.init0 = load i32, ptr %steps.addr
  br label %while.cond
while.cond:
  %n.phi0 = phi i32 [%n.init0, %while.pre], [%n.merge1, %while.latch]
  %n.phi0 = phi i32 [%n.init0, %while.pre], [%n.merge1, %while.latch]
  %steps.phi0 = phi i32 [%steps.init0, %while.pre], [%steps.next0, %while.latch]
  %t0 = icmp ne i32 %n.phi0, 1
  br i1 %t0, label %while.body, label %while.end
while.body:
  ; while body
  ; if condition
  %t1 = srem i32 %n.phi0, 2
  %t2 = icmp eq i32 %t1, 0
  br i1 %t2, label %then1, label %else1
then1:
  ; then
  ; set n
  %n.next10 = sdiv i32 %n.phi0, 2
  br label %endif1
else1:
  ; else
  ; set n
  %t3 = mul i32 %n.phi0, 3
  %n.next11 = add i32 %t3, 1
  br label %endif1
endif1:
  %n.merge1 = phi i32 [%n.next10, %then1], [%n.next11, %else1]
  ; set steps
  %steps.next0 = add i32 %steps.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.end:
  ; return
  ret i32 %steps.phi0
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @collatz_steps(i32 13)
  %t1 = add i32 %t0, 33
  ret i32 %t1
}

