; generated by weavec2
; source: test/performance/wir/73_factorial_iter_i32.wir
; core-version: 1

; function: factorial
; params: i32
; returns: i32
define i32 @factorial(i32 %n) {
entry:
  %i.addr = alloca i32
  %acc.addr = alloca i32
  ; let i
  store i32 2, ptr %i.addr
  ; let acc
  store i32 1, ptr %acc.addr
  ; while condition
  br label %while.pre
while.pre:
  %acc.init0 = load i32, ptr %acc.addr
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %acc.phi0 = phi i32 [%acc.init0, %while.pre], [%acc.next0, %while.latch]
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp sle i32 %i.phi0, %n
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; set acc
  %acc.next0 = mul i32 %acc.phi0, %i.phi0
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %acc.phi0, ptr %acc.addr
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t1 = load i32, ptr %acc.addr
  ret i32 %t1
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @factorial(i32 7)
  ret i32 %t0
}

