; generated by weavec2
; source: test/performance/wir/76_trial_division_prime_i32.wir
; core-version: 1

; function: is_prime
; params: i32
; returns: i32
define i32 @is_prime(i32 %n) {
entry:
  %d.addr = alloca i32
  %prime.addr = alloca i32
  ; if condition
  %t0 = icmp slt i32 %n, 2
  br i1 %t0, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  ; let d
  store i32 2, ptr %d.addr
  ; let prime
  store i32 1, ptr %prime.addr
  ; while condition
  br label %while.cond1
while.cond1:
  %t1 = load i32, ptr %prime.addr
  %t2 = icmp ne i32 %t1, 0
  %t3 = load i32, ptr %d.addr
  %t4 = load i32, ptr %d.addr
  %t5 = mul i32 %t3, %t4
  %t6 = icmp sle i32 %t5, %n
  %t7 = and i1 %t2, %t6
  br i1 %t7, label %while.body1, label %while.end1
while.body1:
  ; while body
  ; if condition
  %t8 = load i32, ptr %d.addr
  %t9 = srem i32 %n, %t8
  %t10 = icmp eq i32 %t9, 0
  br i1 %t10, label %then2, label %endif2
then2:
  ; then
  ; set prime
  store i32 0, ptr %prime.addr
  br label %endif2
endif2:
  ; set d
  %t11 = load i32, ptr %d.addr
  %t12 = add i32 %t11, 1
  store i32 %t12, ptr %d.addr
  br label %while.cond1
while.end1:
  ; return
  %t13 = load i32, ptr %prime.addr
  ret i32 %t13
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @is_prime(i32 97)
  %t1 = call i32 @is_prime(i32 91)
  %t2 = mul i32 %t1, 10
  %t3 = add i32 %t0, %t2
  ret i32 %t3
}

