; generated by weavec2
; source: test/performance/wir/77_selection_sort4_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %t0 = sext i32 %index to i64
  %t1 = getelementptr i32, ptr %base, i64 %t0
  ret ptr %t1
}

; function: select4
; params: ptr
; returns: i32
define i32 @select4(ptr %items) {
entry:
  %i.addr = alloca i32
  %min_idx.addr = alloca i32
  %j.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp slt i32 %t0, 3
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  %t2 = load i32, ptr %i.addr
  ; let min_idx
  store i32 %t2, ptr %min_idx.addr
  %t3 = load i32, ptr %i.addr
  %t4 = add i32 %t3, 1
  ; let j
  store i32 %t4, ptr %j.addr
  ; while condition
  br label %while.cond1
while.cond1:
  %t5 = load i32, ptr %j.addr
  %t6 = icmp slt i32 %t5, 4
  br i1 %t6, label %while.body1, label %while.end1
while.body1:
  ; while body
  ; if condition
  %t7 = load i32, ptr %j.addr
  %t8 = call ptr @elem_ptr(ptr %items, i32 %t7)
  %t9 = load i32, ptr %t8
  %t10 = load i32, ptr %min_idx.addr
  %t11 = call ptr @elem_ptr(ptr %items, i32 %t10)
  %t12 = load i32, ptr %t11
  %t13 = icmp slt i32 %t9, %t12
  br i1 %t13, label %then2, label %endif2
then2:
  ; then
  ; set min_idx
  %t14 = load i32, ptr %j.addr
  store i32 %t14, ptr %min_idx.addr
  br label %endif2
endif2:
  ; set j
  %t15 = load i32, ptr %j.addr
  %t16 = add i32 %t15, 1
  store i32 %t16, ptr %j.addr
  br label %while.cond1
while.end1:
  ; if condition
  %t17 = load i32, ptr %min_idx.addr
  %t18 = load i32, ptr %i.addr
  %t19 = icmp ne i32 %t17, %t18
  br i1 %t19, label %then3, label %endif3
then3:
  ; then
  %t20 = load i32, ptr %i.addr
  %t21 = call ptr @elem_ptr(ptr %items, i32 %t20)
  %t22 = load i32, ptr %t21
  ; let tmp
  %t23 = load i32, ptr %i.addr
  %t24 = call ptr @elem_ptr(ptr %items, i32 %t23)
  %t25 = load i32, ptr %min_idx.addr
  %t26 = call ptr @elem_ptr(ptr %items, i32 %t25)
  %t27 = load i32, ptr %t26
  store i32 %t27, ptr %t24
  %t28 = load i32, ptr %min_idx.addr
  %t29 = call ptr @elem_ptr(ptr %items, i32 %t28)
  store i32 %t22, ptr %t29
  br label %endif3
endif3:
  ; set i
  %t30 = load i32, ptr %i.addr
  %t31 = add i32 %t30, 1
  store i32 %t31, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t32 = call ptr @elem_ptr(ptr %items, i32 0)
  %t33 = load i32, ptr %t32
  ret i32 %t33
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 16)
  ; let items
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @elem_ptr(ptr %t0, i32 0)
  store i32 9, ptr %t2
  %t3 = call ptr @elem_ptr(ptr %t0, i32 1)
  store i32 3, ptr %t3
  %t4 = call ptr @elem_ptr(ptr %t0, i32 2)
  store i32 7, ptr %t4
  %t5 = call ptr @elem_ptr(ptr %t0, i32 3)
  store i32 1, ptr %t5
  %t6 = call i32 @select4(ptr %t0)
  ; let first
  call void @free(ptr %t0)
  ; return
  %t7 = add i32 %t6, 11
  ret i32 %t7
}

