; generated by weavec2
; source: test/performance/wir/78_reverse_array4_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %t0 = sext i32 %index to i64
  %t1 = getelementptr i32, ptr %base, i64 %t0
  ret ptr %t1
}

; function: reverse4
; params: ptr
; returns: i32
define i32 @reverse4(ptr %items) {
entry:
  %left.addr = alloca i32
  %right.addr = alloca i32
  ; let left
  store i32 0, ptr %left.addr
  ; let right
  store i32 3, ptr %right.addr
  ; while condition
  br label %while.pre
while.pre:
  %left.init0 = load i32, ptr %left.addr
  %right.init0 = load i32, ptr %right.addr
  br label %while.cond
while.cond:
  %left.phi0 = phi i32 [%left.init0, %while.pre], [%left.next0, %while.latch]
  %right.phi0 = phi i32 [%right.init0, %while.pre], [%right.next0, %while.latch]
  %t0 = icmp slt i32 %left.phi0, %right.phi0
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  %t1 = call ptr @elem_ptr(ptr %items, i32 %left.phi0)
  %t2 = load i32, ptr %t1
  ; let tmp
  %t3 = call ptr @elem_ptr(ptr %items, i32 %left.phi0)
  %t4 = call ptr @elem_ptr(ptr %items, i32 %right.phi0)
  %t5 = load i32, ptr %t4
  store i32 %t5, ptr %t3
  %t6 = call ptr @elem_ptr(ptr %items, i32 %right.phi0)
  store i32 %t2, ptr %t6
  ; set left
  %left.next0 = add i32 %left.phi0, 1
  ; set right
  %right.next0 = sub i32 %right.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %left.phi0, ptr %left.addr
  store i32 %right.phi0, ptr %right.addr
  br label %while.end
while.end:
  ; return
  %t7 = call ptr @elem_ptr(ptr %items, i32 1)
  %t8 = load i32, ptr %t7
  ret i32 %t8
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 16)
  ; let items
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @elem_ptr(ptr %t0, i32 0)
  store i32 10, ptr %t2
  %t3 = call ptr @elem_ptr(ptr %t0, i32 1)
  store i32 20, ptr %t3
  %t4 = call ptr @elem_ptr(ptr %t0, i32 2)
  store i32 30, ptr %t4
  %t5 = call ptr @elem_ptr(ptr %t0, i32 3)
  store i32 40, ptr %t5
  %t6 = call i32 @reverse4(ptr %t0)
  ; let mid
  call void @free(ptr %t0)
  ; return
  %t7 = add i32 %t6, 5
  ret i32 %t7
}

